(function(e){var g=window.AmazonUIPageJS||window.P,m=g._namespace||g.attributeErrors,b=m?m("WebFlowIngressJs",""):g;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,g,m){e.when("jQuery").register("webflow-fetch-experience",function(b){return{fetchExperience:function(b){return fetch(b,{headers:{Accept:"application/vnd.com.amazon.xa+html"}}).then(function(b){if(b.ok)return b.text();throw Error("Network response: "+b.status);}).then(function(b){return{html:b}}).catch(function(b){return{error:b}})},
buildExperienceUrl:function(e,l){var c=new URL(e,g.location);(new URLSearchParams(b.param(l))).forEach(function(b,a){c.searchParams.set(a,b)});return c.toString()}}});e.when("A","a-modal-framework","a-modal-framework-constants").register("webflow-modal",function(b,e,l){return{presentModal:function(c){c={type:"ajax",source:c};var h='\x3cdiv class\x3d"'+l.CONTENT_WRAPPER_CLASS+'"\x3e\x3c/div\x3e';h=b.$('\x3cdiv style\x3d"background-color:white" class\x3d"overlay-container"\x3e\x3c/div\x3e').append("",
'\x3cbutton class\x3d"overlay-close"\x3e\x3cspan class\x3d"a-icon a-icon-close-white"\x3e\x3c/span\x3e\x3c/button\x3e').append(h);c=new e(h,c,{dismissStrategy:"transient",scrimType:"translucent"});c.present();c=c._frameworkWrapper.find(".overlay-close");b.declarative.create(c,"a-modal-framework-dismiss");b.declarative("a-modal-framework-dismiss",["click","keydown"],function(a){var c=b.$(a.$currentTarget).closest("."+constants.FRAMEWORK_WRAPPER_CLASS);if(0!==c.length&&(c=c.data("overlayInstance"))){var d=
"keydown"===a.type&&a.$event.which===b.constants.keycodes.ESCAPE;("click"===a.type||"persistent"!==c._dismissStrategy&&d)&&c.dismiss()}})}}});e.when().register("webflow-bottomsheet",function(){return{presentBottomSheet:function(b,g){e.logError(null,"presentBottomSheet called on desktop - bottom sheet is not supported on this device","WARN")},isBottomSheetOpen:function(){return!1},closeBottomSheetAndRedirect:function(b){e.logError(null,"closeBottomSheetAndRedirect called on desktop - this should not happen",
"ERROR")}}});e.when("webflow-modal","webflow-bottomsheet","webflow-fetch-experience").register("webflow-routing",function(b,n,l){function c(a){try{g.top.location.href=a}catch(f){e.logError(f,"Could not change the URL in the parent window:"+a,"ERROR")}}function h(a){a&&"function"===typeof a&&a()}return{show:function(a){try{var f=null;if("url"in a.route)f=a.route.url;else if("web"in a.route&&"url"in a.route.web)f=a.route.web.url;else if("flow"in a.route){var d=a.route.flow.inputs||{};d.t0=a.t0!==m?
a.t0:Date.now();f=l.buildExperienceUrl(a.route.flow.endpoint,d)}if(null===f)throw Error("Invalid Options Error: no url found");var k=f;"bottom-sheet"==a.presentationConfig.presentationType&&n.presentBottomSheet(k,a.presentationConfig.bottomSheetConfig);"modal-with-overlay"==a.presentationConfig.presentationType&&b.presentModal(k);"push"==a.presentationConfig.presentationType&&(n.isBottomSheetOpen()?n.closeBottomSheetAndRedirect(k):a.route.url?c(k):a.route.web.url?c(k):(e.logError(null,"fullUrl not available:"+
k+", navigating to fallbackUrl","WARN"),c(a.route.flow.fallbackUrl)));h(a.successCallback)}catch(p){throw h(a.failCallback),p;}}}});e.declare("webflow-skeleton-tmp-icdp",{getSkeleton:function(){function b(){var b=a();b.append(d(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-small"]));return b}function e(){var a=d(["a-section"]);a.append(d(["webflow-skeleton-tmp-icdp-image-block",
"a-spacing-base"]),d(["webflow-skeleton-tmp-icdp-image-swatches","aok-align-center-horizontally"]));return a}function g(){var b=d(),c=a();c.append(d(["webflow-skeleton-tmp-icdp-text-base","a-spacing-mini"]));b.append(f("hr",["a-spacing-mini"]),c,f("hr",["a-spacing-none"]));return b}function c(){var b=d(),c=a(),e=a(),f=a(),g=a();c.append(d(["webflow-skeleton-tmp-icdp-text-tall-mini","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-tall-small","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-small"]));
e.append(d(["webflow-skeleton-tmp-icdp-text-micro"]));f.append(d(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-extra-large"]));g.append(d(["webflow-skeleton-tmp-icdp-text-medium","a-spacing-mini"]),d(["webflow-skeleton-tmp-icdp-text-large"]));b.append(c,e,f,g);return b}function h(){var a=d(["a-row","a-padding-base","webflow-skeleton-tmp-icdp-action-bar"]);a.append(d(["a-column","a-spacing-base","webflow-skeleton-tmp-icdp-button"]),d(["a-column",
"a-spacing-base","webflow-skeleton-tmp-icdp-button","a-span-last"]));return a}function a(){return d(["a-section","a-spacing-none","a-padding-base"])}function f(a,b){a=document.createElement(a);for(var c in b)a.classList.add(b[c]);return a}function d(a){return f("div",a)}return function(){var a=document.createElement("div");a.append(b(),e(),g(),c(),h());return a}()}})});