'use strict';(function(f){var l=window.AmazonUIPageJS||window.P,q=l._namespace||l.attributeErrors,c=q?q("NileInlineCustomerExperienceWidgetDPXAssets",""):l;c.guardFatal?c.guardFatal(f)(c,window):c.execute(function(){f(c,window)})})(function(f,l,q){f.now("nile-inline-state-utils").execute(function(c){c||f.when("A").register("nile-inline-state-utils",function(c){return{getState:function(g){var f=c.state(g);if(f)return f;c.state.parse();return c.state(g)}}})});f.now("nile-inline-widget-instrumentation").execute(function(c){c||
f.when("nile-inline-state-utils").register("nile-inline-widget-instrumentation",function(c){function g(a){var m=Array.from(arguments).slice(1,arguments.length);return function(){for(var k=arguments.length,t=Array(k),b=0;b<k;b++)t[b]=arguments[b];a.apply(void 0,m.concat(t))}}function f(a){a=[a.dataset.blueMetrics,a.dataset.actionId];a=a.filter(function(a){return a!==q&&null!==a&&""!==a});return a.join(":")}function e(a){for(var m=Object.keys(a),k=0;k<m.length;k++){var b=m[k],d=a[b];null===d||d===q?
d="":"number"===typeof d&&(d=d.toString());a[b]=d}return a}function b(a,m){var k=(k=document.cookie.match(/(?:^|;)\s*amzn-app-id\s*=\s*([^\s;]+)/))?k[1].split("/"):[];var b=/(?:^|;)\s*micron\s*=\s*1\s*(?:$|;)/.test(document.cookie);k={name:k[0],version:k[1],isMicron:b};b=document.cookie.match(/(?:^|;)\s*amzn-app-ctxt\s*=\s*\d\.\d?\s*([^\s;]+)/);try{var d=b?JSON.parse(decodeURIComponent(b[1])):""}catch(C){d=""}b=c.getState("dpx-nice-state");a=Object.assign({timestamp:n(new Date),producerId:"mshop-nile",
metadata:'{"program":"'+(b&&b.instrumentationConfig&&b.instrumentationConfig.programOverride||"blue-dpx")+'"}',isBeta:!1,deviceTypeId:d&&d.di&&d.di.dti||"",directedCustomerId:b&&b.directedCustomerId||"",appVersion:k&&k.version||"",locale:b&&b.locale||"UNKNOWN",marketplaceId:b&&b.marketplaceId||"UNKNOWN",uxSessionId:"",sessionId:w()||""},a);"undefined"!==typeof ue&&ue.event(e(a),"mshop-nile",m)}function p(a,m){var b=a.luggage,d=b.items[a.key];if(m=m[0])m.isIntersecting?(d.impressingStartAt=new Date,
b.visibleElems.add(d.key)):d.impressingStartAt&&(d.impressingEndAt=new Date,d.reason=null!=m.rootBounds?"SCROLLED_AWAY":"REMOVED",u(a),d.impressingStartAt=null,d.impressingEndAt=null,b.visibleElems.remove(d.key))}function x(a){var b=a.luggage.items[a.key];b.impressingStartAt&&"visible"!==document.visibilityState&&(document.contains(b.elem)&&(b.impressingEndAt=new Date,b.reason="PAGE_HIDDEN",u(a)),document.removeEventListener("visibilitychange",b.pageVisibilityChangeListener))}function d(a,b){a.chunks.addFromEvent(b)}
function y(a,m,d){a.requestEndAt=new Date;m=a.chunks.markAsRendered(m);if(d&&d[0]){var k=d[0].matches("[data-blue-request-id]")&&d[0]||d[0].querySelector("[data-blue-request-id]");if(k)for(a.requestId=k.dataset.blueRequestId,b({schemaId:"mshop.nile.events.4",eventTimeUTC:n(a.requestStartAt),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE_BACKEND_API",eventDetail:void 0},"mshop.nile.events.4"),d=d.find("[data-blue-metrics]"),k=g(l,a),a.visibilityChangeListenerForLatency=
k,document.addEventListener("visibilitychange",a.visibilityChangeListenerForLatency),k=0;k<d.length;k++){var c=d[k],e=f(c);if(a.items[e])a.items[e].elem=c;else{a.items[e]={key:e,elem:c,name:c.dataset.blueMetrics,detail:c.dataset.actionId};var h=m;b({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:c.dataset.actionId,seqId:h.index,requestStartTimeUTC:n(a.requestStartAt),renderingStartTimeUTC:n(h.renderingStartAt),renderingEndTimeUTC:n(h.renderingEndAt),interruptedTimeUTC:""},"mshop.nile.latency.6")}e=
c={luggage:a,key:e};h=e.luggage.items[e.key];h.elem.observer||(h.elem.observer=new IntersectionObserver(g(p,e),{threshold:.85}),h.elem.observer.observe(h.ghost||h.elem),h.pageVisibilityChangeListener||(h.pageVisibilityChangeListener=g(x,e),document.addEventListener("visibilitychange",h.pageVisibilityChangeListener)));e=c.luggage.items[c.key];e.elem.clickListener||(e.elem.clickListener=g(z,c),e.elem.addEventListener("click",e.elem.clickListener))}}}function h(a,b){a.requestEndAt=new Date;document.removeEventListener("visibilitychange",
a.visibilityChangeListenerForLatency)}function l(a){if("visible"!==document.visibilityState&&!a.requestEndAt){a.interruptedAt=new Date;var d=a.flow.toUpperCase(),k=a.chunks.maybeGetLastRendered();b({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:d,seqId:k?k.index+1:0,requestStartTimeUTC:n(a.requestStartAt),renderingStartTimeUTC:"",renderingEndTimeUTC:"",interruptedTimeUTC:n(a.interruptedAt)},"mshop.nile.latency.6");Object.keys(a.items)}}function u(a){var d=a.luggage;a=d.items[a.key];
b({schemaId:"mshop.nile.impressions.1",nileRequestId:d.requestId,elementId:a.detail||a.name,seqId:a.chunkId||0,requestStartTimeUTC:n(d.requestStartAt),impressionStartTimeUTC:n(a.impressingStartAt),impressionEndTimeUTC:n(a.impressingEndAt),impressionEndReason:a.reason},"mshop.nile.impressions.1")}function z(a){var d=a.luggage.items[a.key];b({schemaId:"mshop.nile.events.4",eventTimeUTC:n(new Date),nileRequestId:a.luggage.requestId,clickstreamRequestId:null,eventName:d.name,eventDetail:d.detail},"mshop.nile.events.4")}
function n(a){return a instanceof Date?a.toISOString():""}function A(a){a=(a=(a=a&&a.event&&a.event.refTarget)&&a.closest("[data-blue-metrics]"))&&a.dataset&&a.dataset.actionId;return/^[a-z][a-z0-9]*(?:_[a-z0-9]+)*_\d_\d+$/.test(a)?a:q}function B(a){return{flow:a.flow,actionId:A(a),chunks:{length:0,addFromEvent:function(a){var b={event:a,renderingStartAt:new Date,index:this.length};a.index=b.index;return[].push.call(this,b)},getFromEvent:function(a){return this[a.index]},maybeGetLastRendered:function(){for(var a=
this.length,b=0;b<a&&this[b].renderingEndAt;b++);return 0===b?null:this[b-1]},markAsRendered:function(a){a=this.getFromEvent(a);a.renderingEndAt=new Date;return a}},requestStartAt:new Date,requestEndAt:null,answer:{},visibleElems:{length:0,add:function(a){this[a]||[].push.call(this,a)},remove:function(a){delete this[a]}},items:{}}}function w(){var a=document.cookie.match(/(?:^|;)\s*session-id\s*=\s*([^\s;]+)/);return a?a[1]:""}var v={};return{executeAndLogMetrics:function(a,b){b=B(b);var c=v.luggage;
c&&(document.removeEventListener("visibilitychange",c.visibilityChangeListenerForLatency),c.answer&&c.answer.observer&&(c.answer.observer.unobserve(c.answer.elem),document.removeEventListener("visibilitychange",c.answer.visibilityChangeListener)));v.luggage=b;b={afterFullRender:g(h,b),beforePillRender:g(d,b),afterPillRender:g(y,b)};a(b)},buildContext:function(a,b){return{flow:a,event:b}}}})});f.now("nile-inline-dpx-lazy-pill-fetch").execute(function(c){c||f.when("A").register("nile-inline-dpx-lazy-pill-fetch",
function(c){function g(){var b=document.querySelector('#rufusInlineCsrfTokenContainer input[name\x3d"anti-csrftoken-a2z"]');return b?b.value:""}function h(b,c){var e=b.querySelectorAll(".nice-shimmer-pill"),d=document.createElement("div");d.innerHTML=c;d.style.position="absolute";d.style.top="0";d.style.left="0";d.style.width="100%";var g=d.querySelectorAll(".dpx-smidget-desktop-pill-list-item, .dpx-multi-row-carousel-card");g.forEach(function(b){b.style.opacity="0";b.style.transform="translateY(20px)"});
var h=document.createElement("div");h.style.position="relative";b.parentNode.insertBefore(h,b);h.appendChild(b);h.appendChild(d);var f=d.querySelector(".dpx-multi-row-carousel-container"),p=d.querySelector(".dpx-multi-row-carousel-viewport");f&&(f.style.overflow="visible");p&&(p.style.overflowX="visible",p.style.overflowY="visible");requestAnimationFrame(function(){for(var b=Math.max(e.length,g.length),d=0;d<b;d++)(function(b){var d=120*b;e[b]&&setTimeout(function(){e[b].style.transition="opacity 120ms linear";
e[b].style.opacity="0"},d);g[b]&&setTimeout(function(){g[b].style.transition="opacity 120ms linear, transform 400ms cubic-bezier(0.25, 0.46, 0.45, 0.94)";g[b].style.opacity="1";g[b].style.transform="translateY(0)"},d)})(d)});var l=document.querySelector("#dpx-nice-widget-container");setTimeout(function(){f&&(f.style.overflow="");p&&(p.style.overflowX="",p.style.overflowY="");l.style.height=l.offsetHeight+"px";l.style.overflow="hidden";d.style.position="";d.style.top="";d.style.left="";d.style.width=
"";b.remove();var c=l.scrollHeight;l.style.transition="height 200ms ease";requestAnimationFrame(function(){l.style.height=c+"px"});setTimeout(function(){l.style.height="";l.style.overflow="";l.style.transition="";for(var b=document.createDocumentFragment();d.firstChild;)b.appendChild(d.firstChild);h.parentNode.replaceChild(b,h)},200)},120*Math.max(e.length,g.length)+400)}function e(b){var c=b[0]||b;c.style.height=c.offsetHeight+"px";c.style.overflow="hidden";requestAnimationFrame(function(){c.style.transition=
"opacity 200ms linear, height 400ms ease";c.style.opacity="0";c.style.height="0"});setTimeout(function(){c.style.display="none"},400)}return{fetchAndReplacePills:function(){var b=c.$("#dpx-nice-shimmer");if(b.length){var f=c.$("#dpx-nice-widget-container"),l=Date.now();c.$.ajax({url:"/rufus/web/lazyLoad",type:"POST",contentType:"application/json",dataType:"html",timeout:5E3,headers:{"anti-csrftoken-a2z":g()},data:JSON.stringify({asin:b.data("asin"),refererRequestId:b.data("referer-request-id"),programId:b.data("program-id")||
"BLUE_DPX",productGroup:b.data("product-group")}),success:function(d){var c=Date.now()-l;ue&&ue.count&&ue.count("RUFUS_DPX_LAZY_LOAD_LATENCY",c);ue&&ue.count&&ue.count("RUFUS_DPX_LAZY_LOAD_SUCCESS",1);d&&d.trim()?h(b[0],d):(e(f),ue&&ue.count&&ue.count("RUFUS_DPX_LAZY_LOAD_EMPTY",1))},error:function(){ue&&ue.count&&ue.count("RUFUS_DPX_LAZY_LOAD_FAILURE",1);e(f)}})}}}})});f.now("nile-inline-dpx-desktop-sponsored-click-handler").execute(function(c){c||f.when("A").register("nile-inline-dpx-desktop-sponsored-click-handler",
function(){function c(c){fetch(c,{method:"POST",mode:"no-cors",cache:"no-store"}).then(function(){"undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED_CLICK_URL_SUCCESS",1)}).catch(function(c){"undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED_CLICK_URL_FAILURE",1)})}return{handleSponsoredPillClick:function(g){var f="sponsoredEvergreenPill"===g.data.variant;g=g.data.actionUrl;f&&g&&("undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED",
1),c(g));return f}}})});f.when("A").execute(function(c){function h(c,b){var e,f=new Promise(function(d){e=setTimeout(function(){d("timeout")},b)});c=c();return Promise.race([c,f]).then(function(b){clearTimeout(e);return b})}function g(){return new Promise(function(e){f.when("rufus-eligible").execute(function(){l._dpxRufusConnectRegistered||(l._dpxRufusConnectRegistered=!0,c.declarative("dpx-rufus-connect","click",function(b){b.$currentTarget.find(".ask-pill").length?l.P.now("rufus-handle-expand").execute(function(b){b&&
b("NileRelatedQuestionIngress")}):l.P.when("nile-inline-dpx-desktop-sponsored-click-handler").execute(function(c){var e=c.handleSponsoredPillClick(b);l.P.when("rufus-handle-stream").execute(function(c){c&&(ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK_SENT_TO_RUFUS_DESKTOP",1),c({qis:e?"NileDPSmidgetSponsoredRelatedQuestionIngress":"What do customers say?"===b.data.query?"NileNDSWDCSRelatedQuestion":"NileRelatedQuestionIngress",query:b.data.query,metricName:"BlueDPXIngress"}))})})}));e("resolved")})})}
function r(){h(g,50).then(function(e){"timeout"===e&&f.now("rufus-eligible").execute("hide-dpx-widget",function(b){b===q&&c.$("#dpx-nice-widget-container").hide(0)})}).catch(function(e){c.$("#dpx-nice-widget-container").hide(0)})}r();c.on("PageRefresh:ATF",r)});f.when("A","nile-inline-widget-instrumentation","nile-inline-dpx-lazy-pill-fetch").execute(function(c,f,g){(function(){var h=f.buildContext("pills");f.executeAndLogMetrics(function(e){var b={type:"default_pills"};e.beforePillRender(b);e.afterPillRender(b,
c.$("#dpx-nice-widget-container"))},h);g.fetchAndReplacePills()})()})});