(function(e){var k=window.AmazonUIPageJS||window.P,n=k._namespace||k.attributeErrors,p=n?n("CustomerReviewsCommonAssets",""):k;p.guardFatal?p.guardFatal(e)(p,window):p.execute(function(){e(p,window)})})(function(e,k,n){function p(){}e.when("ready").execute(function(){function b(){return function(b,g){e.now?e.now(b).execute(function(c){c||e.register(b,g)}):e.register(b,g)}}e.now?e.now("cr-register-helper").execute(function(d){d||e.register("cr-register-helper",b)}):e.register("cr-register-helper",
b)});"use strict";e.when("A","cr-log-utils","cr-streaming-utils","cr-register-helper","ready").execute(function(b,d,g,c){c("cr-ajax-model",function(){function a(a){m[a]&&(m[a].abort(),delete m[a])}function c(f,h,q,r,u,e,x,n){h=h||{};h.params=h.params||{};e=e?e:t++;u=u?u:h.error||function(){};r=r?r:0;q=q?q:2;n=n?n:"FATAL";var z="FATAL"===n?0:1,v=h.finallyCallback||function(){};x||(x="reviewsAjax"+l++,k.uet&&k.uet("tc",x));var w=b.state("cr-weblab-state"),p;for(p in w)w.hasOwnProperty(p)&&(h.params[p]=
w[p]);h.params.scope=x;h.contentType=h.contentType||"application/x-www-form-urlencoded;charset\x3dUTF-8";var y=h.success||function(){};h.success=function(a){delete m[e];"function"===typeof y&&y(a);"function"===typeof v&&v(a)};h.error=function(b,l,m){b=b||{};var g=(b.http||{}).status||"[]";if(401===g){var t=b;var p=u,w=t.http.getResponseHeader("x-amz-re-authentication-url");w?("function"===typeof p&&p(t),"function"===typeof v&&v(t),d.logCount("AjaxRedirectToReAuthenticationUrl",1),k.location=w,t=!0):
t=!1;if(t)return;r=q}a(e);r++;r<q?(l="AJAX Post to "+f+" from "+k.location.href+" failed, status code passed through parameter was: "+l+", status code extracted from XHR HTTP object was: "+g+", attempt "+r+" of "+q+", error message was: \n "+m,d.logError(l,"WARN"),c(f,h,q,r,u,e,x,n)):(l="AJAX Post to "+f+" from "+k.location.href+" failed, status code passed through parameter was: "+l+", status code extracted from XHR HTTP object was: "+g+", exhausted "+q+" attempt(s), error message was: \n "+m,d.logError(l,
n),d.logCount("AjaxFailureFatal",z),"function"===typeof u&&u(b),"function"===typeof v&&v(b))};"function"!==typeof h.chunk&&(h.chunk=function(a){"appendFadeIn"===a[0]?g.appendFadeIn(a):"replace"===a[0]&&g.replace(a)});m[e]=b.post(f,h);return e}var l=0,t=1,m={};return{abort:a,post:c,postWithoutFatals:function(a,b,l,f,d,m,g){return c(a,b,l,f,d,m,g,"WARN")}}})});"use strict";e.when("A","cr-jQuery","cr-log-utils","cr-number-utils","cr-register-helper","ready").execute(function(b,d,g,c,a){a("cr-A",function(){b.toggleExpanderAriaLabel=
function(a,c,d){a="a:expander:"+a+":toggle";b.on(a+":expand",function(a){a.expander.$expander.find('a[data-action\x3d"a-expander-toggle"]').attr("aria-label",d);a.expander.$expander.attr("tabindex","-1").focus()});b.on(a+":collapse",function(a){a.expander.$expander.find('a[data-action\x3d"a-expander-toggle"]').attr("aria-label",c)})};b.getListFromState=function(a){var l=b.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return b.reduce(l,function(b,l){l!==n&&l[a]!==
n&&b.push(l[a]);return b},[])};b.getValueFromState=function(a){var l=b.getListFromState(a);1<l.length&&g.logError("More than one  value defined for key: "+a,"ERROR");return l[0]};var a={top:-100,left:-100};b.inView=function(b){b=b||d();if("function"===typeof b.offset){var l=(b.offset()||a).top-d(k).scrollTop();b=0<=l;l=l<d(k).height();return b&&l}return!1};b.onScreenAndVisible=function(a,b){a=a||d();b=c.isFiniteNumber(b)?b:0;if(a instanceof d||a.jquery){if(!a.is(":visible"))return!1;a=a[0].getBoundingClientRect();
return a.top>=0-b&&a.left>=0-b&&a.bottom<=d(k).height()+b&&a.right<=d(k).width()+b}return!1};b.compositeEventWrapper=function(a,c,d){var f=a;d&&(f=b.throttle(f,d,{trailing:!1}));return g.jsGuard(function(a){a&&(f(a),c&&a.$event&&a.$event.preventDefault())})};b.freeze=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):a};b.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return b})});"use strict";
e.when("jQuery","cr-register-helper","ready").execute(function(b,d){d("cr-jQuery",function(){return b})});"use strict";e.when("ready").execute(function(){function b(){e.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",
RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",
VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",OPEN_MASH_MODAL:"reviews:open-mash-modal",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",
FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",
SELECT_PRODUCT_LINK:"reviews:select-product-link",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click",TRIGGER_WEBLAB:"reviews:trigger-weblab",REFTAG_TRIGGER:"reviews:trigger-reftag"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",
FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage",HEIGHT_KEY:"filterByHeight",WEIGHT_KEY:"filterByWeight"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}})}
e.now?e.now("reviews-constants").execute(function(d){d||b()}):b()});"use strict";e.when("A","cr-string-utils","cr-log-utils","cr-register-helper","ready").execute(function(b,d,g,c){c("cr-popup",function(){function a(a){var c={};a&&a.data&&(c=a.data);var f=d.defaultIfBlank(c.url,a.$target.find("a").andSelf().filter("a").attr("href")),m=d.defaultIfBlank(c.title,"CustomerReviews");m=""+m;var e="";b.each({width:null,height:null,resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,b){var d=
c[b];a=null===d||d===n?a:d;null!==a&&(e+=b+"\x3d"+a+",")});e=e.slice(0,-1);var h=null;try{(h=k.open(f,m,e))?h.focus():g.logError("Unable to move focus to popup window with data: "+d.stringify(c),"ERROR"),a.$event.preventDefault()}catch(q){g.logError("Unable to open window with parameters: "+d.stringify(c),"FATAL",q)}return h}b.declarative("cr-popup",["click"],g.jsGuard(a));return{popup:a}})});"use strict";e.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view",
"cr-register-helper","ready").execute(function(b,d,g,c,a,f,l){l("cr-generic-declarative-actions",function(){function a(a){h(a)&&a.data.selector&&a.data.cssClass&&(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),b.trigger("a:pageUpdate"))}function l(a){h(a)&&a.data.scrollToSelector&&(f.scrollTo(a.data.scrollToSelector,0),a.$event.preventDefault())}function e(a){if(h(a)&&a.data.url&&a.data.params){a.$event.preventDefault();b.declarative.remove(a.$currentTarget,r.AJAX_POST);
a=a.data;var f=a.params,l=d(a.indicatorSelector)[0],g=q(d.fn.hide,a.hideOnSuccessSelector),m=q(d.fn.show,a.showOnFailureSelector);d(a.removeOnLoadSelector).remove();c.post(a.url,{params:f,indicator:l,success:g,error:m})}}function h(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function q(a,b){if(b&&"function"===typeof a)return function(){var c=d(b);0<c.length&&a.call(c)}}var r=g.events;b.declarative(r.TOGGLE_CLASS_CLICK,"click",a);b.declarative(r.SCROLL_TO_ELEMENT_CLICK,
"click",l);b.declarative(r.AJAX_POST,"click",e);return{toggleCssClass:a,scrollToElement:l,ajaxPost:e}})});"use strict";e.when("cr-register-helper","ready").execute(function(b){b("cr-global-model",function(){return{generateUrl:function(b,g){b&&"/"!==b.charAt(b.length-1)&&(b+="/");b&&g&&(b=b+"ref\x3d"+g);return b}}})});"use strict";e.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils","cr-register-helper","ready").execute(function(b,d,g,c,a,f){f("cr-global-view",function(){function f(b){var c=
"";if(b&&b.closest!==n){var f=b.closest("*["+h.REFTAG+"]");f&&(c=f.attr(h.REFTAG))}a.isBlank(c)&&b&&b.closest!==n&&(b=b.closest("*[rel]"))&&(c=b.attr("rel"));return a.defaultIfBlank(c,"cm_cr_unknown")}function e(a){return a&&"function"===typeof a.is?a.is("*["+h.getReviews.CHECKED+"]")&&a.is("*["+h.getReviews.UNCHECKED+"]"):!1}function m(a){return a&&a.has!==n&&a.is!==n?0<a.find(":checked").length||a.is(":checked"):!1}function k(b,c){return b&&b.attr!==n&&c?a.parseJSON(b.attr(c))||{}:{}}var h=c.data;
b.on("a:pageUpdate",function(){d!==n&&d.initializeExpanders()});b.on(c.events.RELOAD_COMPLETE,function(){b.trigger("a:image:lazyLoad")});(function(){function a(a){a&&a.addEventListener("focusout",function(){a.classList.remove("cr-remove-focus-visible")},!1)}function b(a,b){a&&b&&a.addEventListener("click",function(a){a.target.closest("a[href]:not(:focus-visible)")&&b.classList.add("cr-remove-focus-visible")},!1)}var c=document.getElementById("acrCustomerReviewLink"),f=document.getElementById("aw-udpv3-customer-reviews_feature_div"),
d=document.getElementById("mobile-product-reviews");b(d,d);a(d);b(f,f);a(f);b(c,f)})();return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(h.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),f;c&&a&&a.closest!==n&&(f=a.closest(c));return e(f)?m(f)?k(f,h.getReviews.CHECKED):k(f,h.getReviews.UNCHECKED):k(f,h.getReviews.STANDARD)},getReftag:function(a){if(a&&a.$target)var b=a.$target;a&&a.id&&(b=g("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=
f(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:f,scrollTo:function(a,b){a=g(a).offset();b=b||0;var c=g("#cr-state-object").data("state");c=c!==n&&c.disableScroll;a&&a.top!==n&&!c&&(g("html,body").stop(),g("html,body").animate({scrollTop:a.top-b},{queue:!1,duration:500}))}}})});"use strict";e.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","cr-string-utils","cr-uri-utils","cr-register-helper","ready").execute(function(b,
d,g,c,a,f,l,e,m){m("cr-lazy-widget-controller",function(){function m(f){var d=b.getValueFromState("lazyWidgetDomainWhitelist"),m=e.getCurrentHostname();if(d)b:{for(var h=0;h<d.length;h++)if(l.endsWith(m,d[h])){a.logCount("LazyWidgetInvalidDomain",0);break b}a.logError("AJAX triggered from invalid domain: "+m,"WARN");a.logCount("LazyWidgetInvalidDomain",1)}else a.logCount("LazyWidgetInvalidDomain",1),a.logError("AJAX triggered with null whitelist from domain: "+m,"WARN");g.loadLazyWidgets(c.getLazyWidgetStubs())&&
(a.logCount("LazyWidgetTrigger",1),a.logCount("LazyWidgetTrigger:"+f,1))}var h={};h.bufferPixels=f.convertToInteger(b.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);h.delayBeforeTriggering=f.convertToInteger(b.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);h.triggerLazyLoadIfWidgetWithinBuffer=function(a){g.lazyLoadHasTriggered()||c.getLazyWidgetStubs().each(function(a,c){if(b.onScreen(d(c),h.bufferPixels))return m("scroll"),!1})};var k={};h.logVisibleStubMetrics=function(f){c.getLazyWidgetStubs().each(function(c,
f){c=d(f);f=c.data("widget-name");!k[f]&&b.onScreen(c)&&(a.logCount("VisibleLazyWidgetStub",1),a.logCount("VisibleLazyWidgetStub:"+f,1),k[f]=!0)})};b.on("scroll",h.logVisibleStubMetrics);b.on("scroll",h.triggerLazyLoadIfWidgetWithinBuffer);d(c.getHoverTargets()).mouseenter(function(){m("hover")});a.logCount("LazyWidgetTrigger",0);return b.freeze(h)})});"use strict";e.when("cr-A","cr-ajax-model","cr-uri-utils","cr-register-helper","ready").execute(function(b,d,g,c){c("cr-lazy-widget-model",function(){function a(){var a=
b.$("#cr-state-object").attr("data-lazy-widget-triggered");return a===n?e:"true"===a}var c={},l=b.getValueFromState("lazyWidgetLoaderUrl"),e=!1;c.loadLazyWidgets=function(c){if(!a()&&0<c.length){e=!0;b.$("#cr-state-object").attr("data-lazy-widget-triggered","true");var f=b.getValueFromState("asin"),m=b.getValueFromState("lazyWidgetCsrfToken"),k=b.getValueFromState("languageOfPreference");c=b.reduce(c,function(a,c){return a+"\x26lazyWidget\x3d"+b.$(c).data("widget-name")},l+"?asin\x3d"+f+"\x26csrf\x3d"+
m+"\x26language\x3d"+k);d.postWithoutFatals(c,{success:p,cache:!1,headers:{"cache-control":"no-cache"},params:g.getUrlParametersMap()||{}});return!0}return!1};c.lazyLoadHasTriggered=function(){return a()};return b.freeze(c)})});"use strict";e.when("cr-A","cr-jQuery","cr-register-helper","ready").execute(function(b,d,g){g("cr-lazy-widget-view",function(){var c={},a=b.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";c.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};c.getHoverTargets=
function(){d(a)};return b.freeze(c)})});"use strict";e.when("A","cr-register-helper","ready").execute(function(b,d){d("cr-log-utils",function(){function b(a,b,c){k.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?k.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):k.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:b,jsGuard:function(a){if("function"===
typeof a)return function(){try{return a.apply(this,arguments)}catch(f){b("Uncaught Error in function","FATAL",f)}};b("Unable to wrap non-function","ERROR");return a},incrementCount:function(a,b){k.ue&&(a=c(a,b),b=k.ue.count(a)||0,k.ue.count(a,b+1))},logCount:function(a,b,d){k.ue&&(a=c(a,d),k.ue.count(a,b))}}})});"use strict";e.when("A","reviews-constants","cr-register-helper","ready").execute(function(b,d,g){g("cr-mash-utils",function(){function c(a){e.when("mash").execute(function(b){b.navstack.begin().modalOpen(a).end()})}
var a=!1;e.when("mash").execute(function(){a=!0});b.declarative(d.events.OPEN_MASH_MODAL,"click",function(a){c(a.data.url);a.$event.preventDefault()});return{isMash:function(){return a},openModal:c}})});"use strict";e.when("A","cr-log-utils","cr-register-helper","ready").execute(function(b,d,g){g("cr-number-utils",function(){return{convertToInteger:function(b,a){if(b===parseInt(b,10))return b;if(null!==b&&"string"===typeof b&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(a!==n)return a;d.logError("convertToInteger",
"Cannot convert "+b+" to Integer");return 0},isFiniteNumber:function(b){return"number"===typeof b&&!isNaN(b)&&isFinite(b)}}})});"use strict";e.when("cr-A","reviews-constants","cr-ajax-model","cr-global-model","cr-register-helper","ready").execute(function(b,d,g,c,a){a("cr-reftag-utils",function(){function a(a){g.postWithoutFatals(a)}b.declarative(d.events.REFTAG_TRIGGER,"click",function(b){b.data.refMarker&&b.data.reftagTriggerUrl&&a(b.data.reftagTriggerUrl+"/ref\x3d"+b.data.refMarker)});return{triggerRefTagWithUrl:a,
triggerRefTag:function(d){var f=b.getValueFromState("reftagTriggerUrl");f&&d&&a(c.generateUrl(f,d))}}})});"use strict";e.when("A","cr-jQuery","cr-register-helper","ready").execute(function(b,d,g){g("cr-streaming-utils",function(){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var a=c[1];c=d(c[2]).hide();d(a).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}},replace:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var a=b[2];d(b[1]).replaceWith(d(a))}}}})});
"use strict";e.when("A","cr-log-utils","cr-register-helper","ready").execute(function(b,d,g){g("cr-string-utils",function(){function c(a){return null===a||a===n?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,parseJSON:function(a){try{return b.parseJSON(a)}catch(f){d.logError("Unable to parse JSON object","ERROR",f)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},endsWith:function(a,b){if(a===b)return!0;if(null===
a||null===b)return!1;var c=a.lastIndexOf(b);return-1!==c&&c===a.length-b.length},stringify:function(a){return k.JSON&&k.JSON.stringify?k.JSON.stringify(a):a}}})});"use strict";e.when("A","cr-register-helper","ready").execute(function(b,d){d("cr-uri-utils",function(){function d(){return k.location.hostname}function c(a){a=a||k.location.href;var c={},d=a.indexOf("?"),e=a.indexOf("#");a=a.slice(d+1,e>d?e:n)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&(d=[a]);b.each(d,function(a,
b){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),c[a[0]]=a[1])});return c}return{getUrlParametersMap:c,addKeyValuePair:function(a,b,d){d=d||0;if(c(a)[b]===d||!a||!b)return a;b="?"+b+"\x3d"+d;return-1<a.indexOf("?")?a.replace("?",b+"\x26"):a+b},getCurrentHostname:d,getDomainRealmBaseUrl:function(a){a=a||d();if(-1!==a.indexOf(".corp.amazon.com"))return"https://development.amazon.com/";if(-1!==a.indexOf(".proxy.amazon.com")){a=a.split(".")[1];var b={dub:"https://pre-prod.amazon.co.uk/",pdx:"https://pre-prod.amazon.co.jp/",
pek:"https://pre-prod.amazon.cn/"};return b[a]!==n?b[a]:"https://pre-prod.amazon.com/"}return"/"}}})});"use strict";e.when("A","reviews-constants","cr-register-helper","ready").execute(function(b,d,e){e("cr-weblab-utils",function(){function c(a){k.ue&&k.ue.trigger&&k.ue.trigger(a.weblabID,a.treatment)}b.declarative(d.events.TRIGGER_WEBLAB,"click",function(a){a.data.weblab&&a.data.treatment&&c({weblabID:a.data.weblab,treatment:a.data.treatment})});return{triggerWeblab:c}})});"use strict";e.when("A",
"cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery","cr-register-helper","ready").execute(function(b,d,e,c,a,f){f("cr-extended-uri-utils",function(){function f(){return c(k.location.href)}function g(){return f().query()}return a.extend(d,{getCurrentUri:f,getCurrentQueryString:g,getCurrentQueryParameters:function(){return c.parseQuery(g())},isAmazonDomain:function(a){if("string"===typeof a||a instanceof String)a=c(a);var b=e.startsWith(a.domain(),"amazon");!1===b&&(a=a.hostname(),a=a.substring(a.indexOf(".")+
1),b=e.startsWith(a,"amazon"));return b},setQueryParameters:function(a,d){if("string"===typeof a||a instanceof String)a=c(a);b.each(d,function(b,c){e.isBlank(b)?a.removeSearch(c):a=a.setSearch(c,b)});return a},setReftag:function(a,b){if("string"===typeof a||a instanceof String)a=c(a);for(var d=a.segment(),f=!1,g=d.length-1;0<=g;g--)if(e.startsWith(d[g],"ref\x3d")){f=!0;d[g]="ref\x3d"+b;break}f||d.push("ref\x3d"+b);a.segment(d);return a}})})});"use strict";e.when("A","cr-jQuery","cr-lazy-widget-controller",
"cr-register-helper","ready").execute(function(b,d,e,c){c("histogram-trigger",function(){function a(){b.onScreen(d("#histogramTable"))&&(e.logVisibleStubMetrics(),e.triggerLazyLoadIfWidgetWithinBuffer())}b.on.afterLoad(a);return{triggerHistogram:a}})});"use strict";e.when("A","cr-register-helper","ready").execute(function(b,d){d("cm-cr-sticky-translate-cookie-handler-allreviews-hz",function(){function d(a){var b=new Date;b.setHours(b.getHours()+1);document.cookie="cm-cr-sticky-translate\x3d"+a+"; expires\x3d"+
b.toUTCString()+"; path\x3d/"}function c(){document.cookie="cm-cr-sticky-translate\x3d; expires\x3dThu, 01 Jan 1970 00:00:00 UTC; path\x3d/"}b.on("cm-cr-sticky-translate-set",function(a){"1"===a||"2"===a?d(a):c()});return{setCookie:d,deleteCookie:c,getCookie:function(){var a=document.cookie.match(/(^| )cm-cr-sticky-translate=([^;]+)/);return a?a[2]:null}}})})});
/* ******** */
(function(e){var n=window.AmazonUIPageJS||window.P,t=n._namespace||n.attributeErrors,f=t?t("CustomerReviewsVotingAssets",""):n;f.guardFatal?f.guardFatal(e)(f,window):f.execute(function(){e(f,window)})})(function(e,n,t){e.when("A","cr-jQuery","a-checkbox","a-modal","3p-urijs","cr-extended-uri-utils","cr-log-utils","cr-register-helper","ready").execute(function(f,q,c,a,m,h,r,e){e("report-abusive-review-controller",function(){function k(b){var a=[];f.each(q("[id^\x3dcr-report-abusive-review-reason-"+
b+"]"),function(b,l){c(b).isChecked()&&a.push(b.value)});return a}function e(b){var d=b.data,p=m(d.reportAbuseFeedbackUrl);if(d.isSignedIn){var l=k(d.reviewId);p.setSearch("customerSelections",l.join(","));a.get(q("#report-abusive-review-modal-popover-"+d.reviewId)).update({url:p.toString()}).lock().show()}else d=d.reviewId,l=h.getCurrentUri(),l.hash(d),p.setSearch("openid.return_to",encodeURI(l)),n.location.href=p.toString();b.$event.preventDefault()}function g(b){var d=b.data,p=b.$target;d={url:d.url,
width:d.width,header:d.header,name:d.name};var l=a.get(p);l?l.update(d).refresh():l=a.create(p,d);l.show();b.$event.preventDefault()}f.declarative("reviews:report-abusive-review-submit-action","click",e);f.declarative("reviews:report-abusive-review-modal-button","click",g);f.on("a:popover:ajaxFail",function(b){(b=b.popover)&&b.name&&0==b.name.indexOf("report-abusive-review-modal-popover-")&&r.logCount("AjaxFailure:ReportAbusiveReview",1)});f.on("a:popover:invisible",function(b){(b=b.popover)&&b.name&&
0==b.name.indexOf("report-abusive-review-modal-popover-")&&a.remove(b)});return{submitAbusiveReviewReport:e,showReportAbusiveReviewModal:g}})});"use strict";e.when("A","cr-jQuery","a-checkbox","a-sheet","vote-model","vote-view","cr-log-utils","cr-register-helper","ready").execute(function(f,e,c,a,m,h,r,u){u("report-abusive-review-mobile-controller",function(){function k(b){var a=[];f.each(e("[id^\x3dcr-report-abusive-review-reason-"+b+"]"),function(b,p){c(b).isChecked()&&a.push(b.value)});return a}
function q(b){b=a.get("report-abusive-review-bottom-sheet-"+b);a.hideSheet(b)}function g(a,d){b(a,d);h.showElementByCssSelector(a,d.inFlight)}function b(b,a){h.hideElementByCssSelector(b,a.hideVoteComponents);a.hideAbuseComponents&&h.hideElementByCssSelector(b,a.hideAbuseComponents)}function d(a,d){var c=k(d.reviewId);d.additionalAjaxParams={customerSelections:c.join(",")};q(d.reviewId);a=e("#report-abusive-review-button-"+d.reviewId);g(a,d.cssSelectors);m.submitVote(d,function(c){if(!0===c){c=a;
var g=d.cssSelectors;b(c,g);h.showElementByCssSelector(c,g.onSuccess)}else c=a,g=d.cssSelectors,b(c,g),h.showElementByCssSelector(c,g.onError)},function(c){if(401===c.http.status){if(c.http.getResponseHeader("x-amz-re-authentication-url")){r.logCount("Ajax401WithReAuthUrl:SubmitVote",1);return}r.logCount("Ajax401WithoutReAuthUrl:SubmitVote",1)}c=a;var g=d.cssSelectors;b(c,g);h.showElementByCssSelector(c,g.onError)})}f.declarative("reviews:vote-action-multi-selection","click",function(a){d(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:d}})});"use strict";e.when("A","vote-model","vote-view","a-modal","cr-log-utils","cr-register-helper","ready").execute(function(f,e,c,a,m,h){h("vote-controller",function(){function h(a,b){k(a,b);c.showElementByCssSelector(a,b.onError);c.setFocus(a,".cr-vote-focusable-error")}function q(a,b){k(a,b);c.showElementByCssSelector(a,b.inFlight);c.setFocus(a,".cr-vote-focusable-feedback")}function k(a,b){c.hideElementByCssSelector(a,b.hideVoteComponents);
b.hideAbuseComponents&&c.hideElementByCssSelector(a,b.hideAbuseComponents)}function n(g,b){b.isReportAbuse&&(g=f.$("#mobile-abuse-"+b.reviewId),a.get(g).hide());q(g,b.cssSelectors);e.submitVote(b,function(a){if(!0===a){a=g;var d=b.cssSelectors;k(a,d);c.showElementByCssSelector(a,d.onSuccess);c.setFocus(a,".cr-vote-focusable-success")}else h(g,b.cssSelectors)},function(a){if(401===a.http.status){if(a.http.getResponseHeader("x-amz-re-authentication-url")){m.logCount("Ajax401WithReAuthUrl:SubmitVote",
1);return}m.logCount("Ajax401WithoutReAuthUrl:SubmitVote",1)}h(g,b.cssSelectors)})}f.declarative("reviews:vote-action","click",function(a){n(a.$target,a.data);a.$event.preventDefault()});return{submitVote:n}})});"use strict";e.when("A","cr-ajax-model","cr-register-helper","ready").execute(function(f,e,c){c("vote-model",function(){return{submitVote:function(a,c,f){var m={"anti-csrftoken-a2z":a.csrfT};a.physicalId&&a.imageExtension&&(m["x-amz-extra-params"]=[a.physicalId,a.imageExtension]);var h={reviewId:a.reviewId},
k;for(k in a.additionalAjaxParams)h[k]=a.additionalAjaxParams[k];e.post(a.ajaxUrl,{params:h,attribution:"submitVote",success:c,error:f,headers:m})}}})});"use strict";e.when("A","cr-register-helper","ready").execute(function(f,e){e("vote-view",function(){function c(a,c){return a.closest(".cr-vote").find(c)}return{hideThankYouAlert:function(a){c(a,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(a){c(a,".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(a){c(a,
".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(a){c(a,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(a){c(a,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(a){c(a,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(a,e){c(a,e).addClass("aok-hidden")},showElementByCssSelector:function(a,e){c(a,e).removeClass("aok-hidden")},setFocus:function(a,e){c(a,e).focus()}}})})});
/* ******** */
(function(h){var A=window.AmazonUIPageJS||window.P,B=A._namespace||A.attributeErrors,f=B?B("CustomerReviewsGalleryAssets",""):A;f.guardFatal?f.guardFatal(h)(f,window):f.execute(function(){h(f,window)})})(function(h,A,B){h.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded","cr-register-helper","ready").execute(function(f,b,e,c,k,m){m("review-image-binder",function(){function p(a,d,g,l,c){if(!(a&&d&&g instanceof b&&l instanceof b&&c instanceof b))return e.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+
a+", galleryName: "+d+", $popoverTrigger: "+g+", $thumbnails: "+l+", $galleryLink: "+c,"FATAL"),!1;var q="reviewsLightbox-ready-"+d;l.click(function(){k(a,d);var e=l.index(this);g.click();h.when(q).execute(function(){b("#"+d).trigger("jumpToImageAtIndex",e)})});c.click(function(){k(a,d);g.click();h.when(q).execute(function(){b("#"+d).trigger("hideImmersiveView")})});return!0}function k(b,d){if(!b||!d)return e.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+b+", galleryName: "+
d,"FATAL"),!1;if(m)return!0;(new ReviewsLightbox(d,"DESKTOP")).initializeForAsin(b);return m=!0}var m=!1,a={};h.when("reviewsLightbox-js").execute(function(){var a=b("#reviews-image-gallery-container"),d=a.attr("data-asin");0<a.length&&d&&p(d,"reviews-image-gallery",a.find(".a-popover-trigger"),a.find(".review-image-tile"),a.find(".reviews-image-gallery-link"))});f.on(c.events.RELOAD_COMPLETE,function(){a={}});return{bindReview:function(e,d,c){var l=new ReviewGallery(c,"DESKTOP"),g=b("#"+d);g.find(".review-image-tile").each(function(d){b(this).click(function(){a[e]||
(l.initializeForReview(e),a[e]=!0);g.find(".a-popover-trigger").click();h.when("reviewsLightbox-ready-"+c).execute(function(){l.render();l.showImageAtIndex(d)})})})},initializeImageGallery:k,initializeEventHandlers:p}})});"use strict";h.when("A","cr-jQuery","cr-image-popover-data-fetcher","cr-see-all-images-controller","cr-register-helper","ready").execute(function(f,b,e,c,k){k("cr-image-popover-controller",function(){function k(){for(var a=0;a<y.length;a++)a!=n&&b(y[a]).unbind("click").removeClass("cr-lightbox-selected").removeAttr("aria-pressed"),
b(y[a]).click(p(a));l(n)}function p(b){return function(){C(b)}}function f(e){C(e);d();q()&&b(v).focus();a()&&b(w).focus()}function r(){b(w).unbind("click");b(v).unbind("click");1===y.length?(b(w).css(E),b(v).css(E)):(b(w).click(function(){f(parseInt(n,10)+1)}).focus(d).blur(g),b(v).click(function(){f(parseInt(n,10)-1)}).focus(d).blur(g),b(Q).mouseenter(d).mouseleave(g))}function a(){var b=e.getReviewIds();return!D&&0===n||D&&0===n&&0==b.indexOf(G)}function q(){var b=e.getReviewIds();return!D&&n===
z.length-1||D&&n===z.length-1&&b.indexOf(G)==b.length-1}function d(){w.css(M);v.css(M);q()&&w.css(E);a()&&v.css(E);w.animate(N,100);v.animate(N,100)}function g(){w.animate(X,100);v.animate(X,100)}function l(b){0<=b&&b<z.length&&(b=y.eq(b).find("img").attr("alt"))&&H.attr("alt",b)}function C(a){if(0<=a&&a<z.length)H.attr("src",z[a]),b(y[n]).removeClass("cr-lightbox-selected").attr("aria-pressed","false"),b(y[a]).addClass("cr-lightbox-selected").attr("aria-pressed","true"),n=a;else if(D){var ha=e.getReviewList(),
d=e.getReviewIds(),c=d.indexOf(G),g={popover:{$trigger:{context:{}}}};a>n?(c++,c<d.length&&(g.popover.$trigger.context.id=d[c]+"-0",F(g))):(c--,-1<c&&(g.popover.$trigger.context.id=d[c]+"-"+(ha[d[c]].images.length-1),F(g)))}l(n)}function u(a){b(O).empty();a.forEach(function(a,d){d=d===n?"cr-lightbox-image-thumbnail cr-lightbox-selected":"cr-lightbox-image-thumbnail";b(O).append(b("\x3cimg\x3e",{src:a,class:d}))});y=t.find(".cr-lightbox-image-button");k()}function W(a,d,e,c){t=(D=c||!1)?b("#cr_customers_image_gallery"):
b("#"+a+"_image_popover");L=t.closest('[role\x3d"dialog"]');I=t.closest(".a-popover-wrapper").find("h4.a-popover-header-content");w=t.find(".cr-lightbox-navigator-button__next");v=t.find(".cr-lightbox-navigator-button__back");y=t.find(".cr-lightbox-image-button");Q=t.find(".cr-lightbox-image-viewer");H=Q.find(".cr-lightbox-main-image");A=t.find(".cr-lightbox-review-title");B=t.find(".cr-lightbox-review-body");Y=t.find(".cr-lightbox-review-origin");R=t.find(".cr-lightbox-review-rating");O=t.find(".cr-lightbox-image-thumbnails");
D&&(P=t.find(".cr-lightbox-customer-profile"),S=t.find(".cr-lightbox-customer-profile .a-profile-name"),Z=t.find(".cr-lightbox-customer-profile .a-profile-avatar \x3e img"),U=R.find(".a-icon-alt"));z=d;"string"===typeof d&&(z=d.substring(1,d.length-1).split(","));k();C(h(e).thumbnailId||0);r();if(a=t.data("heading"))I.attr("aria-label",a),L.attr("aria-label",a)}function F(b){var a=e.getReviewList();e.getReviewIds();for(var d=h(b).reviewId,c=[],g=[],l=0;l<a[d].images.length;l++)c.push(a[d].images[l].source),
g.push(a[d].images[l].lowResSource);G=d;W(d,c,b,!0);b=G;A.text(a[b].title);R.removeClass();R.addClass("a-icon a-icon-star a-star-"+a[b].starRating+" cr-lightbox-review-rating");U.text(U.text().replace(/\d([.,]\d)?/,a[b].starRating+".0"));u(g);B.text(a[b].reviewText);Y.text(a[b].originDescription);D&&(a=a[b],null===a.customerProfileLink||0===a.customerProfileLink.length?P.css("cursor","initial"):P.css("cursor",""),P.attr("href",a.customerProfileLink),S.text(a.customerName),Z.attr("src",a.customerProfileImage));
J(!1)}function h(b){return b&&b.popover&&b.popover.$trigger&&b.popover.$trigger.context&&(b=b.popover.$trigger.context.id)&&(b=b.split("-"),1<b.length)?{reviewId:b[0],thumbnailId:parseInt(b[1],10),seeAllImages:!1}:{seeAllImages:!0}}function aa(b){h(b).seeAllImages?J(!0):F(b)}function J(a){t=b("#cr_customers_image_gallery");a?(t.hide(),T.show(),c.updateSeeAllImages(T,F),H&&H.attr("src","")):(t.show(),T.hide(),x.hide(),ba.show(),ca.removeClass("cr-lightbox-review-row-no-display"),ca.addClass("cr-lightbox-review-row"))}
var M={cursor:"pointer",display:"block"},E={cursor:"auto",display:"none"},N={opacity:1},X={opacity:0},L,I,z,n=0,w,v,y,Q,H,G,D=!1,K=!1,A,B,Y,R,O,P,S,Z,U,T=b("#seeAllImagesContainer"),t=b("#cr_customers_image_gallery"),x=b(".cr-large-loadingIcon"),ca=b("#crReviewRow"),ba=b("#crViewAllImagesLink");return{initImagePopover:W,loadDataAndInitImageGalleryPopover:function(b,a,d,c){e.isDataLoaded()?aa(b):e.fetchData(d,a,c,function(a,c){if(a=!K)a:{a=e.getReviewIds();for(c=0;c<d.length;c++)if(0>a.indexOf(d[c])){a=
!1;break a}a=!0}a&&(aa(b),K=!0)})},toggleSeeAllView:J}})});"use strict";h.when("A","cr-jQuery","cr-image-popover-data-fetcher","cr-ranking-see-all-images-controller","cr-register-helper","ready").execute(function(f,b,e,c,k){k("cr-ranking-image-popover-controller",function(){function k(){for(var a=0;a<y.length;a++)a!=n&&b(y[a]).unbind("click").removeClass("cr-lightbox-selected").removeAttr("aria-pressed"),b(y[a]).click(p(a));l(n)}function p(b){return function(){C(b)}}function f(c){C(c);d();q()&&b(v).focus();
a()&&b(w).focus()}function r(){b(w).unbind("click");b(v).unbind("click");1===y.length?(b(w).css(E),b(v).css(E)):(b(w).click(function(){f(parseInt(n,10)+1)}).focus(d).blur(g),b(v).click(function(){f(parseInt(n,10)-1)}).focus(d).blur(g),b(Q).mouseenter(d).mouseleave(g))}function a(){var b=e.getReviewIds();return!K&&0===n||K&&0===n&&0==b.indexOf(D)}function q(){var b=e.getReviewIds();return!K&&n===z.length-1||K&&n===z.length-1&&b.indexOf(D)==b.length-1}function d(){w.css(M);v.css(M);q()&&w.css(E);a()&&
v.css(E);w.animate(N,100);v.animate(N,100)}function g(){w.animate(B,100);v.animate(B,100)}function l(b){0<=b&&b<z.length&&(b=y.eq(b).find("img").attr("alt"))&&H.attr("alt",b)}function C(a){if(0<=a&&a<z.length)H.attr("src",z[a]),b(y[n]).removeClass("cr-lightbox-selected").attr("aria-pressed","false"),b(y[a]).addClass("cr-lightbox-selected").attr("aria-pressed","true"),n=a;else if(K){e.getReviewList();var d=e.getReviewIds(),c=d.indexOf(D),g={popover:{$trigger:{context:{}}}};a>n?(a=G[d[c]],c++,c<d.length&&
(g.popover.$trigger.context.dataset={reviewid:d[c],physicalid:Object.keys(a)[0]},F(g))):(c--,-1<c&&(a=G[d[c]],g.popover.$trigger.context.dataset={reviewid:d[c],physicalid:Object.keys(a)[Object.keys(a).length-1]},F(g)))}l(n)}function u(a){b(P).empty();a.forEach(function(a,d){d=d===n?"cr-lightbox-image-thumbnail cr-lightbox-selected":"cr-lightbox-image-thumbnail";b(P).append(b("\x3cimg\x3e",{src:a,class:d}))});y=x.find(".cr-lightbox-image-button");k()}function W(a,d,c,e){x=(K=e||!1)?b("#cr_customers_image_gallery"):
b("#"+a+"_image_popover");L=x.closest('[role\x3d"dialog"]');I=x.closest(".a-popover-wrapper").find("h4.a-popover-header-content");w=x.find(".cr-lightbox-navigator-button__next");v=x.find(".cr-lightbox-navigator-button__back");y=x.find(".cr-lightbox-image-button");Q=x.find(".cr-lightbox-image-viewer");H=Q.find(".cr-lightbox-main-image");ea=x.find(".cr-lightbox-review-title");Y=x.find(".cr-lightbox-review-body");R=x.find(".cr-lightbox-review-origin");O=x.find(".cr-lightbox-review-rating");P=x.find(".cr-lightbox-image-thumbnails");
K&&(S=x.find(".cr-lightbox-customer-profile"),Z=x.find(".cr-lightbox-customer-profile .a-profile-name"),U=x.find(".cr-lightbox-customer-profile .a-profile-avatar \x3e img"),T=O.find(".a-icon-alt"));z=d;"string"===typeof d&&(z=d.substring(1,d.length-1).split(","));k();C(h(c).thumbnailId||0);r();if(a=x.data("heading"))I.attr("aria-label",a),L.attr("aria-label",a)}function F(a){var b=e.getReviewList();e.getReviewIds();for(var d=h(a).reviewId,c=[],g=[],l=0;l<b[d].images.length;l++)c.push(b[d].images[l].source),
g.push(b[d].images[l].lowResSource);D=d;W(d,c,a,!0);a=D;ea.text(b[a].title);O.removeClass();O.addClass("a-icon a-icon-star a-star-"+b[a].starRating+" cr-lightbox-review-rating");T.text(T.text().replace(/\d([.,]\d)?/,b[a].starRating+".0"));u(g);Y.text(b[a].reviewText);R.text(b[a].originDescription);K&&(b=b[a],null===b.customerProfileLink||0===b.customerProfileLink.length?S.css("cursor","initial"):S.css("cursor",""),S.attr("href",b.customerProfileLink),Z.text(b.customerName),U.attr("src",b.customerProfileImage));
J(!1)}function h(b){if(b&&b.popover&&b.popover.$trigger&&b.popover.$trigger.context&&b.popover.$trigger.context.dataset){var a=b.popover.$trigger.context.dataset.reviewid,d=b.popover.$trigger.context.dataset.physicalid;if(!b.popover.$trigger.context.dataset.seemore&&a&&d)return{reviewId:a,thumbnailId:G[a][d],seeAllImages:!1}}return{seeAllImages:!0}}function A(b){h(b).seeAllImages?J(!0):F(b)}function J(a){x=b("#cr_customers_image_gallery");a?(x.hide(),t.show(),c.updateSeeAllImages(t,F),H&&H.attr("src",
"")):(x.show(),t.hide(),ca.hide(),fa.show(),ba.removeClass("cr-lightbox-review-row-no-display"),ba.addClass("cr-lightbox-review-row"))}var M={cursor:"pointer",display:"block"},E={cursor:"auto",display:"none"},N={opacity:1},B={opacity:0},L,I,z,n=0,w,v,y,Q,H,G={},D,K=!1,da=!1,ea,Y,R,O,P,S,Z,U,T,t=b("#seeAllImagesContainer"),x=b("#cr_customers_image_gallery"),ca=b(".cr-large-loadingIcon"),ba=b("#crReviewRow"),fa=b("#crViewAllImagesLink");return{initImagePopover:W,loadDataAndInitImageGalleryPopover:function(b,
a,d,c){e.isDataLoaded()?A(b):e.fetchData(d,a,c,function(a,c){if(a=!da)a:{a=e.getReviewIds();for(c=0;c<d.length;c++)if(0>a.indexOf(d[c])){a=!1;break a}a=!0}if(a){a=e.getReviewList();for(var g in a){c={};for(var l=0;l<a[g].images.length;l++){var k=a[g].images[l].source;var f=k.lastIndexOf("/")+1;k=k.substring(f);f=k.lastIndexOf(".");f=k.substring(0,f);c[f]=l}G[a[g].reviewId]=c}A(b);da=!0}})},toggleSeeAllView:J,setReviewToPhysicalIdAndIndexMap:function(a){G=a}}})});"use strict";h.when("A","cr-jQuery",
"cr-log-utils","cr-register-helper","ready").execute(function(f,b,e,c){c("cr-image-popover-data-fetcher",function(){function c(a,b,c){a="/hz/reviews-render/get-reviews-with-media?mediaType\x3dimage\x26asin\x3d"+a+"\x26csrfToken\x3d"+b;c!==B&&(a+="\x26nextToken\x3d"+c);return a}function m(a,b,g,l,k,u){g=c(b,g,u);f.ajax(g,{method:"get",success:function(d){for(var c in d.reviewsWithMediaList)r[c]=d.reviewsWithMediaList[c];c=Object.keys(r);h=a.slice();for(var e=0;e<c.length;e++)0>a.indexOf(c[e])&&h.push(c[e]);
"function"===typeof l&&l(r,h);d.nextToken?m(a,b,d.csrfToken,l,k,d.nextToken):p=!0},error:function(a){e.logCount("ReviewWithImages-DataFetcher-Error");"function"===typeof k&&k()}})}var p=!1,h=[],r={},a=null;return{fetchData:m,getReviewList:function(){return r},getReviewIds:function(){return h},isDataLoaded:function(){return p},getCustomerImageAltText:function(){a||(a=b(".review-with-images-section .cr-customer-image-thumbnail")[0].getAttribute("alt"));return a}}})});"use strict";h.when("A","cr-jQuery",
"cr-image-popover-data-fetcher","cr-register-helper","ready").execute(function(f,b,e,c){c("cr-see-all-images-controller",function(){function c(a,c,d,g){a=b("\x3cdiv\x3e",{class:"cr-thumbnail-preview-tile",css:{background:"url("+a+") 50% 50% no-repeat"},role:"img",alt:e.getCustomerImageAltText()});a.click(function(){g({popover:{$trigger:{context:{id:c+"-"+d}}}})});return a}function f(a,b,d){for(var g=e.getReviewList(),l=e.getReviewIds(),f=p;p<f+d;){var k=l[r];if(k&&g[k]){r++;for(var m=0;m<g[k].images.length;m++){var q=
"undefined"===typeof h[k+m]?!0:!1;q&&(a.append(c(g[k].images[m].lowResSource,k,m,b)),p++,0==p%7&&a.append("\x3cbr /\x3e"),h[k+m]=k+m)}}else break}}var p=0,h={},r=0;return{updateSeeAllImages:function(a,b){f(a,b,50);var d=0;a.scroll(function(){var c=a.scrollTop();200<c-d&&(d=c,f(a,b,50))})}}})});"use strict";h.when("A","cr-jQuery","cr-image-popover-data-fetcher","cr-register-helper","ready").execute(function(f,b,e,c){c("cr-ranking-see-all-images-controller",function(){function c(a,c,d,g){a=b("\x3cdiv\x3e",
{class:"cr-thumbnail-preview-tile",css:{background:"url("+a+") 50% 50% no-repeat"},role:"img",alt:e.getCustomerImageAltText()});a.click(function(){g({popover:{$trigger:{context:{dataset:{reviewid:c,physicalid:d}}}}})});return a}function f(a,b,d){for(var g=e.getReviewList(),l=e.getReviewIds(),k=p;p<k+d;){var f=l[r];if(f&&g[f]){r++;for(var m=0;m<g[f].images.length;m++){var q="undefined"===typeof h[f+m]?!0:!1;if(q){var V=g[f].images[m].source;q=V.lastIndexOf("/")+1;V=V.substring(q);q=V.lastIndexOf(".");
q=V.substring(0,q);a.append(c(g[f].images[m].lowResSource,f,q,b));p++;0==p%7&&a.append("\x3cbr /\x3e");h[f+m]=f+m}}}else break}}var p=0,h={},r=0;return{updateSeeAllImages:function(a,b){f(a,b,50);var d=0;a.scroll(function(){var c=a.scrollTop();200<c-d&&(d=c,f(a,b,50))})}}})});"use strict";h.when("A","cr-jQuery","cr-register-helper","ready").execute(function(f,b,e){e("cr-mobile-image-popover-controller",function(){function c(a,b){return 0<=a&&a<b.length}function e(){var a=L.prop("scrollHeight"),b=L.prop("clientHeight");
return a>b}function m(){return A.hasClass("cr-mg-image-popover-expand-full-cr")}function p(){e()?(I.removeClass("cr-mg-image-popover-reviews-expand-hide"),I.addClass("cr-mg-image-popover-reviews-expand-show")):(I.removeClass("cr-mg-image-popover-reviews-expand-show"),I.addClass("cr-mg-image-popover-reviews-expand-hide"))}function h(){z.removeClass("cr-mg-image-popover-reviews-content-expand-container-short")}function r(){A.removeClass("cr-mg-image-popover-expand-full-cr");h();L.scrollTop(0);w||C.removeClass("button-hide");
v||l.removeClass("button-hide")}function a(){A.addClass("cr-mg-image-popover-expand-full-cr");h();e()||z.addClass("cr-mg-image-popover-reviews-content-expand-container-short");l.addClass("button-hide");C.addClass("button-hide")}function q(a,c){F.text(c[a].title);B.removeClass();B.addClass("cr-mg-image-popover-reviews-star-rating a-icon a-icon-star-small a-star-small-"+c[a].starRating);aa.text(c[a].reviewText);J.empty();J.append(c[a].richReviewText);M.empty();M.append(b("\x3cimg\x3e",{src:c[a].image,
class:"cr-mg-image-element"}));var d=c[a].authorAvatarImage;E.text(c[a].authorName);N.empty();N.append(b("\x3cimg\x3e",{src:d,"data-src":d}),b("\x3cnoscript\x3e").append(b("\x3cimg\x3e",{src:d})));X.attr("href",c[a].authorProfileLink);a+1==c.length?l.addClass("button-hide"):l.removeClass("button-hide");0==a?C.addClass("button-hide"):C.removeClass("button-hide");p()}function d(a){v=w=0;0==n&&(w=1);n+1==a.length&&(v=1)}function g(a,e){l.unbind("click");C.unbind("click");n=a;d(e);b(l).click(function(){c(n+
1,e)&&(n++,q(n,e),d(e))});b(C).click(function(){c(n-1,e)&&(n--,q(n,e),d(e))})}var l,C,u,A,F,B,aa,J,M,E,N,X,L,I,z,n,w,v;f.declarative("cr-mg-image-popover-expand-review-content","click",function(b){e()&&!m()&&a()});f.declarative("cr-mg-image-popover-reviews-collapse-review-content","click",function(a){r()});f.on("resize",function(){var b=u?u.is(":visible"):!1;b&&(m()?(r(),p(),e()&&a()):p())});return{initializePopover:function(a,d){a=parseInt(a,10);c(a,d)&&(u=b("#cr-mg-immsersive-view-container-"+a),
A=u.find(".cr-mg-image-popover-overlay"),l=u.find(".next-button-mobile"),C=u.find(".back-button-mobile"),F=u.find(".cr-mg-image-popover-review-title"),B=u.find(".cr-mg-image-popover-reviews-star-rating"),aa=u.find(".cr-mg-image-popover-reviews-plain-text"),J=u.find(".cr-mg-image-popover-reviews-rich-text"),M=u.find(".cr-mg-image-view"),L=u.find(".cr-mg-image-popover-reviews-content-wrapper"),I=u.find(".cr-mg-image-popover-reviews-expand-container"),z=u.find(".cr-mg-image-popover-reviews-content-expand-container"),
E=u.find(".cr-mg-image-popover-reviews-reviewer-text"),N=u.find(".a-profile-avatar"),X=u.find(".cr-mg-image-popover-reviews-author-profile-image"),q(a,d),g(a,d))}}})});"use strict";h.when("cr-A","cr-jQuery","cr-streaming-utils","cr-media-gallery-view","cr-media-gallery-model","cr-register-helper","ready").execute(function(f,b,e,c,k,m){m("cr-media-gallery-controller",function(){function p(){return 480<b(A).width()?3:2}function m(){var a=c.getCurrentMasonryItems(),b=p();0<a.length&&(a=c.getPreciseMaxMasonryListHeightItems(a,
b),c.setMasonryListHeight(a.heightInPixelOfColumn,"px",a.nItemInColumn*q))}function h(a){if(!(f.objectIsEmpty(a)||f.objectIsEmpty(a.data)||a.data.isMixedMediaEnabled&&("0"===a.data.count||0<b(a.$currentTarget).has(".cr-mg-filter-btn-selected").length))){c.toggleMediaListLoadingState(!0);var d=k.updateMediaType(a.data.mediaType);c.updateFilterBar(d);k.getMedia(a.data,function(){},function(){},function(){c.toggleMediaListLoadingState(!1)},function(a){"appendFadeIn"===a[0]&&(c.removeMasonryItemLoadingElements(),
e.appendFadeIn(a))})}}function a(){b(".a-manually-loaded.cr-mg-image-element").not("[src]").each(function(){var a=b(this);a.is(":visible")&&f.onScreen(a,g)&&f.loadImageManually(a)})}f.on("resize",function(){c.isMediaGalleryPageVisible()?m():d=!0});f.on("scroll",a);var q=8,d=!1,g=500;return{initialize:m,getNoOfColumns:p,initializeAfterPopoverHide:function(){d&&m();d=!1},initializeMediaFilters:function(a,b){k.setInitialParams(a,b);f.declarative("cr:media-filter","click",f.compositeEventWrapper(h,!0,
100))},manualLazyLoadImages:a}})});"use strict";h.when("A","cr-jQuery","cr-register-helper","ready").execute(function(f,b,e){e("cr-media-gallery-view",function(){return{getCurrentMasonryItems:function(){return b(".cr-mg-masonry-list").find(".cr-mg-masonry-item")},setMasonryListHeight:function(c,e,f){var k=b(".cr-mg-masonry-list-height-control").get(0);k&&(k.style.setProperty("--height-to-column-width",c+e),k.style.setProperty("--height-in-pixel",f+"px"))},getPreciseMaxMasonryListHeightItems:function(c,
e){for(var f=Array(e),k=Array(e),h=0;h<e;h++)f[h]=0,k[h]=0;var r=0;c.each(function(){var a=b(this).children(".cr-mg-ratio-control");f[r%e]+=a.get(0).getBoundingClientRect().height;k[r%e]+=1;r++});c=f.indexOf(Math.max.apply(Math,f));return{heightInPixelOfColumn:f[c],nItemInColumn:k[c]}},isMediaGalleryPageVisible:function(){var c=b(".cr-mg-masonry-list-height-control");return c?c.is(":visible"):!1},updateFilterBar:function(c){var e="image"===c,f="video"===c;c="mixed"===c;b(".cr-mg-filter-btn-vid").toggleClass("cr-mg-filter-btn-selected",
f);b(".cr-mg-filter-btn-img").toggleClass("cr-mg-filter-btn-selected",e);b(".cr-mg-filter-btn-mixed").toggleClass("cr-mg-filter-btn-selected",c)},toggleMediaListLoadingState:function(c){b(".cr-mg-masonry-list-loading").toggleClass("aok-hidden",!c)},removeMasonryItemLoadingElements:function(){b(".cr-mg-masonry-item-loading").remove()}}})});"use strict";h.when("cr-A","cr-log-utils","cr-ajax-model","cr-register-helper","ready").execute(function(f,b,e,c){c("cr-media-gallery-model",function(){var c={},
h;return{setInitialParams:function(b,e){c.asin=b;c.mediaType=e},updateMediaType:function(b){if("image"===b||"video"===b||"mixed"===b)c.mediaType=b;return c.mediaType},getMedia:function(k,m,r,a,q){h&&e.abort(h);var d=f.now();b.logCount("GetMedia:Count",1);h=e.post("/portal/customer-reviews/ajax/media/get/?ie\x3dUTF8",{params:c,attribution:"getMedia",headers:{"anti-csrftoken-a2z":k.csrfToken},success:function(){var a=f.now()-d;b.logCount("GetMedia:Status",1);b.logCount("GetMedia:RequestTime",a);m()},
error:function(){b.logCount("GetMedia:Status",0);r()},finallyCallback:function(){a();h=0},timeout:3E4,chunk:q,cache:!0},1)}}})});"use strict";h.when("A","cr-jQuery","cr-register-helper","ready").execute(function(f,b,e){e("cr-review-inline-images-controller",function(){function c(c){return b("#%s-cr-inline-images-preview".replace("%s",c)).find(".cr-review-inline-images-main-image")}f.declarative("cr-review-inline-images-thumbnail-click","click",function(b){var e=b.data.imageSrc;c(b.data.reviewId).attr("src",
e)});return{getMainImage:c,getAllThumbnails:function(c){return b("#%s-cr-inline-images-preview".replace("%s",c)).find(".cr-review-inline-images-thumbnails .cr-review-inline-images-thumbnail")}}})});"use strict";h.when("cr-inline-videos-controller").execute(function(f){f.initialize(!0)});"use strict";h.when("A","reviews-constants","cr-log-utils","cr-inline-videos-view","cr-vse-brila-player-gateway","cr-register-helper","ready").execute(function(f,b,e,c,h,m){m("cr-inline-videos-controller",function(){function k(b){c.getPlayerPlaceholders().each(function(d,
e){d=f.$(e);if(!c.isPlayerRequestPending(d)&&(!b||b&&c.isPlayerPlaceholderInViewport(d))){c.markPlayerRequestAsPending(d);e=c.extractVideoAsset(d);var g=f.$("#cr-state-object").data("state");e={videoUrl:e.videoUrl,thumbnailUrl:e.thumbnailUrl,reviewId:e.reviewId,closedCaptions:e.closedCaptions,vseContentId:e.vseContentId,marketplaceId:g.marketplaceId,locale:g.locale,page:g.page||"cr_page",placement:g.page?g.page+"_cr_inline_review":"cr_inline_review"};h.getVideoPlayer("vse_reviews_desktop_"+e.reviewId+
"_"+f.now(),e,m(e),r(d),a(d))}})}function m(a){return!f.objectIsEmpty(a)&&!f.objectIsEmpty(a.vseContentId)&&""!=a.vseContentId}function r(a){return function(b){c.markPlayerRequestAsDone(a);c.renderPlayer(a,b)}}function a(a){return function(b){c.markPlayerRequestAsDone(a);c.showErrorMessage(a);e.logError("Failed loading inline video player: "+JSON.stringify(b),"ERROR")}}function q(a){if(a)f.on(f.constants.BROWSER_EVENTS.SCROLL,function(){k(!0)});f.on(b.events.RELOAD_COMPLETE,function(){k(a)})}return{initialize:function(a){k(a);
q(a)},fetchVideoPlayers:k}})});"use strict";h.when("A","cr-register-helper","ready").execute(function(f,b){b("cr-inline-videos-view",function(){return{getPlayerPlaceholders:function(){return f.$(".cr-video-desktop-placeholder")},extractVideoAsset:function(b){b=b.data();return{reviewId:b.reviewId,videoUrl:b.videoUrl,thumbnailUrl:b.thumbnailUrl,closedCaptions:b.closedCaptions,vseContentId:b.vseContentId}},markPlayerRequestAsPending:function(b){b.data("playerRequestPending",!0)},markPlayerRequestAsDone:function(b){b.removeData("playerRequestPending");
b.removeClass("cr-video-desktop-placeholder")},isPlayerRequestPending:function(b){b=b.data("playerRequestPending");return"undefined"!==b&&b},isPlayerPlaceholderInViewport:function(b){return f.onScreen(b,800)},renderPlayer:function(b,c){b.html(c)},showErrorMessage:function(b){b.addClass("cr-media-show-error-msg")}}})});"use strict";h.when("A","cr-uri-utils","cr-log-utils","cr-ajax-model","cr-register-helper","ready").execute(function(f,b,e,c,k){k("cr-vse-brila-player-gateway",function(){function k(b,
a,c){var d={requester:"vse_reviews_desktop",clientPrefix:b,marketplaceID:a.marketplaceId,locale:a.locale,page:a.page,placement:a.placement};c&&a.vseContentId?d.video={contentID:a.vseContentId,contentIDType:"VIDEO_ID"}:(a.videoUrl&&a.thumbnailUrl&&a.reviewId||e.logCount(p("vse_player:${placement}:incomplete_video_payload",a),1),d.video={videoURL:a.videoUrl,imageURL:a.thumbnailUrl,contentID:a.reviewId,contentIDType:"EXTERNAL_VIDEO_ID"},f.objectIsEmpty(a.closedCaptions)||""==a.closedCaptions||(d.video.closedCaptions=
a.closedCaptions));h.now("Brila").execute("vse-assets-check",function(a){a!==B&&(d.excludeAssets=["Brila","VSEPlayer"])});return d}function p(b,a){return b.replace("${placement}",a.placement)}var A=b.getDomainRealmBaseUrl()+"vap/ew/subcomponent/vseplayer";return{getVideoPlayer:function(b,a,h,d,g){var l=f.now();b={params:k(b,a,h),paramsFormat:"json",crossDomain:!0,method:"post",contentType:"application/json",withCredentials:!0,timeout:4E3,success:function(b){var c=f.now()-l;e.logCount(p("vse_player:${placement}:load:status",
a),1);e.logCount(p("vse_player:${placement}:load:request_time",a),c);"function"===typeof d&&d(b)},error:function(b){e.logCount(p("vse_player:${placement}:load:status",a),0);"function"===typeof g&&g(b)}};e.logCount(p("vse_player:${placement}:load:count",a),1);c.post(A,b,2)}}})})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,n=m._namespace||m.attributeErrors,e=n?n("CustomerReviewsFilteringAssets",""):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,n){g.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils","cr-register-helper","ready").execute(function(e,f,a,d,t,c,l,k){k("cr-filtering-controller",function(){function k(h){var c=!1,b=!1;h.toggleFilters&&(b=!0);
d.setASIN(a.getLoadedFilterParam("asin"));c=d.setReviewerType(h.reviewerType,b)||c;c=d.setFormatType(h.formatType,b)||c;c=d.setFilterByKeyword(h.filterByKeyword,b)||c;c=d.setFilterByLanguage(h.filterByLanguage,b)||c;c=d.setSortOrder(h.sortOrder,b)||c;c=d.setStarFilter(h.filterByStar,b)||c;c=d.setPageNumber(h.pageNumber,b)||c;c=d.setHeightFilter(h.filterByHeight,b)||c;c=d.setWeightFilter(h.filterByWeight,b)||c;c=d.setAgeFilter(h.filterByAge,b)||c;return c=d.setMediaFilter(h.mediaType,b)||c}function p(b){if(k(b.data)||
b.data.forceReload){b.data.sortOrder&&a.setSortDropdown(b.data.sortOrder);a.hideReviewLoadError();a.hideReviews();a.showLoadingSpinner();e.trigger(c.events.FILTER_APPLY_BEGIN,b);var h=a.getLoadedFilterParam("newDPFiltersTreatment",!1);null!==h&&"C"!==h&&(h=d.getFilterParams(),n(h));d.getReviews(function(){a.showReviews();var h=document.querySelector("#cm-cr-filters");h&&e.onScreen(h,0)||!h||!h.scrollIntoView||h.scrollIntoView();"filterByHeight"===d.getActiveTab()&&a.scrollToFilterIndex("filterByHeight");
"filterByWeight"===d.getActiveTab()&&a.scrollToFilterIndex("filterByWeight");"filterByAge"===d.getActiveTab()&&a.scrollToFilterIndex("filterByAge");"filterByStar"===d.getActiveTab()&&a.scrollToFilterIndex("filterByStar");e.trigger(c.events.FILTER_APPLY_SUCCESS,b)},function(){a.showReviewLoadError();e.trigger(c.events.FILTER_APPLY_ERROR,b)},function(){a.hideLoadingSpinner();e.trigger(c.events.FILTER_APPLY_DONE,b);e.trigger(c.events.RELOAD_COMPLETE)},function(b){"appendFadeIn"===b[0]?l.appendFadeIn(b):
"replace"===b[0]&&l.replace(b)},t.getReftag(b));b.data.scrollToSelector&&t.scrollTo(b.data.scrollToSelector,0);b.data.filterByAge&&a.setAgeDropdown(b.data.filterByAge)}}function g(b){b&&b.data&&p(b)}function b(b){b&&b.data&&b.$target&&b.data.filterType&&(b.data[b.data.filterType]=b.$target.val(),p(b))}function q(b){b&&b.data&&b.data.filterType&&(a.deactivateFilterTabHeaders(),a.activateFilterTabHeader(b.data.filterType),a.changeFilterOptionsTo(b.data.filterType),d.setActiveTab(b.data.filterType),
"filterByHeight"!==b.data.filterType&&"filterByWeight"!==b.data.filterType&&"filterByAge"!==b.data.filterType&&"filterByStar"!==b.data.filterType||a.scrollToFilterIndex(b.data.filterType))}function n(b){var a=[c.filterOptions.STAR_KEY,c.filterOptions.AVP_KEY,c.filterOptions.MEDIA_KEY,c.filterOptions.LANGUAGE_KEY,c.filterOptions.HEIGHT_KEY,c.filterOptions.WEIGHT_KEY,"filterByAge"],d=!1,q;for(q in b)a.includes(q)&&"CLEAR_VALUE"!==b[q]&&(d=!0);d?f(".cr-widget-MobileGlobalReviews").addClass("aok-hidden"):
f(".cr-widget-MobileGlobalReviews").removeClass("aok-hidden")}d.setReviewsAjaxUrl(a.getReviewsAjaxUrl());a.enableDesktopDPFilterDropdown();e.declarative(c.events.FILTER_APPLY,"click",e.compositeEventWrapper(g,!0,100));e.declarative(c.events.FILTER_CHANGE,"change",e.compositeEventWrapper(b,!0,100));e.declarative(c.events.FILTER_TAB_CLICKED,"click",q);d.setReviewerType(a.getLoadedFilterParam("reviewerType"),!1);d.setFormatType(a.getLoadedFilterParam("formatType"),!1);d.setFilterByKeyword(a.getLoadedFilterParam("filterByKeyword"),
!1);d.setFilterByLanguage(a.getLoadedFilterParam("filterByLanguage"),!1);d.setStarFilter(a.getLoadedFilterParam("filterByStar"),!1);d.setSortOrder(a.getLoadedFilterParam("sortOrder"),!1);d.setPageNumber(a.getLoadedFilterParam("pageNumber"),!1);d.setHeightFilter(a.getLoadedFilterParam("filterByHeight"),!1);d.setWeightFilter(a.getLoadedFilterParam("filterByWeight"),!1);d.setAgeFilter(a.getLoadedFilterParam("filterByAge"),!1);d.setLanguage(a.getLoadedFilterParam("languageOfPreference"));d.setMediaFilter(a.getLoadedFilterParam("mediaType"),
!1);var u=a.getLoadedFilterParam("newDPFiltersTreatment",!1);null!==u&&"C"!==u?a.getLoadedFilterParam("showStarFilter")?d.setActiveTab("filterByStar"):a.getLoadedFilterParam("showLanguageFilter")?d.setActiveTab("filterByLanguage"):a.getLoadedFilterParam("showHeightFilter")?(d.setActiveTab("filterByHeight"),a.scrollToFilterIndex("filterByHeight")):a.getLoadedFilterParam("showAgeFilter")&&d.setActiveTab("filterByAge"):a.getLoadedFilterParam("showLanguageFilter")?d.setActiveTab("filterByLanguage"):a.getLoadedFilterParam("showHeightFilter")?
(d.setActiveTab("filterByHeight"),a.scrollToFilterIndex("filterByHeight")):a.getLoadedFilterParam("showAgeFilter")?d.setActiveTab("filterByAge"):a.getLoadedFilterParam("showStarFilter")&&d.setActiveTab("filterByStar");return{setFilterParams:k,onFilterApply:g,onFilterChange:b,onFilterTabClicked:q}})});"use strict";g.when("cr-A","cr-ajax-model","cr-register-helper","ready").execute(function(e,f,a){a("cr-filtering-model",function(){function a(){return r.asin||""}function g(){return p||""}function c(b,
c){c?r[b]=c:delete r[b]}function l(b,a,d){var e=!1;b&&a!==n&&(e=k(b)!==a,!e&&d&&(a="CLEAR_VALUE",e=!0),c(b,a));return e}function k(b){return r[b]||""}var r={},p="",m;return{getReviews:function(b,a,c,d,l){var q=p,k={"anti-csrftoken-a2z":e.getValueFromState("reviewsCsrfToken")||""};m&&f.abort(m);l&&(q+="ref\x3d"+l);m=f.post(q,{headers:k,params:r,attribution:"getFilteredReviews",success:b,error:a,finallyCallback:function(){c();m=0},chunk:d})},setASIN:function(b){var d=a()!==b;c("asin",b);return d},getASIN:a,
setReviewsAjaxUrl:function(b){var a=g()!==b;p=b||"";return a},getReviewsAjaxUrl:g,setReviewerType:function(b,a){return l("reviewerType",b,a)},getReviewerType:function(){return k("reviewerType")},setFormatType:function(b,a){return l("formatType",b,a)},getFormatType:function(){return k("formatType")},setFilterByKeyword:function(b,a){return l("filterByKeyword",b,a)},getFilterByKeyword:function(){return k("filterByKeyword")},setFilterByLanguage:function(b,a){return l("filterByLanguage",b,a)},getFilterByLanguage:function(){return k("filterByLanguage")},
setSortOrder:function(b,a){return l("sortBy",b,a)},getSortOrder:function(){return k("sortBy")},setStarFilter:function(b,a){return l("filterByStar",b,a)},getStarFilter:function(){return k("filterByStar")},setPageNumber:function(b,a){return l("pageNumber",b,a)},getPageNumber:function(){return k("pageNumber")},setHeightFilter:function(b,a){return l("filterByHeight",b,a)},getHeightFilter:function(){return k("filterByHeight")},setWeightFilter:function(b,a){return l("filterByWeight",b,a)},getWeightFilter:function(){return k("filterByWeight")},
setAgeFilter:function(b,a){return l("filterByAge",b,a)},getAgeFilter:function(){return k("filterByAge")},getFilterParams:function(){return r||{}},updateFilterParam:c,setActiveTab:function(b){return c("activeTab",b)},getActiveTab:function(){return k("activeTab")},setLanguage:function(b){return c("language",b)},setMediaFilter:function(b,a){return l("mediaType",b,a)},getMediaFilter:function(){return k("mediaType")}}})});"use strict";g.when("cr-A","cr-jQuery","a-dropdown","cr-register-helper","ready").execute(function(e,
f,a,d){d("cr-filtering-view",function(){function d(a){return(f("#cr-state-object").data("state")||{})[a]||""}return{getReviewsAjaxUrl:function(){return(f("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var a=e.getValueFromState("onLoadShowHideElements");f(a).removeClass("aok-hidden")},hideLoadingSpinner:function(){var a=e.getValueFromState("onLoadShowHideElements");f(a).addClass("aok-hidden")},hideReviews:function(){f(".filterable-reviews-content").addClass("aok-hidden")},
showReviews:function(){f(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){f(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){f(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){f(".cr-tab-header-text").removeClass("cr-tab-active").closest("li").removeClass("cr-tab-active-item")},activateFilterTabHeader:function(a){f(".cr-tab-header-text-"+a).addClass("cr-tab-active").closest("li").addClass("cr-tab-active-item")},
changeFilterOptionsTo:function(a){f(".cr-tab-content").addClass("aok-hidden");f(".cr-tab-content-"+a).removeClass("aok-hidden")},getLoadedFilterParam:d,setSortDropdown:function(c){a.getSelect("cm-cr-sort-dropdown").setValue(c)},setAgeDropdown:function(c){c="CLEAR_VALUE"===c?"":c;var d=a.getSelect("cm-cr-age-dropdown");null!==d&&d.setValue(c)},scrollToFilterIndex:function(a){var c=0;var e=d("isCardTreatmentEnabled")?f(".cr-horizontal-scroll-list-cardify-padding ul \x3e *:first-child"):f(".cr-horizontal-scroll-list-padding ul \x3e *:first-child");
var g=f(m).width();a=f("ul#"+a+"-button-list")[0];if(e===n||g===n||a===n)c=-1;else{var p=parseInt(a.dataset.index);e=parseInt(e.css("padding-left").replace("px",""));if(-1!==p){c=e-g/2;for(g=0;g<p;g++)c+=f("#"+a.children[g].firstElementChild.id).outerWidth(!0);c+=f("#"+a.children[p].firstElementChild.id).outerWidth(!0)/2}}0>c||f(".cr-filter-scroll-container").animate({scrollLeft:c},50)},enableDesktopDPFilterDropdown:function(){f("#cm-cr-dp-review-sort-type").removeClass("aok-hidden")}}})});"use strict";
g.when("A","jQuery","cr-log-utils").execute(function(e,f,a){e.$(".cr-filter-tab-button").live("click",function(){a.incrementCount("filters-tab-click")});e.$("#button-one_star").live("click",function(){a.incrementCount("starRating-one-star")});e.$("#button-two_star").live("click",function(){a.incrementCount("starRating-two-star")});e.$("#button-three_star").live("click",function(){a.incrementCount("starRating-three-star")});e.$("#button-four_star").live("click",function(){a.incrementCount("starRating-four-star")});
e.$("#button-five_star").live("click",function(){a.incrementCount("starRating-five-star")});e.$("#button-positive").live("click",function(){a.incrementCount("starRating-positive")});e.$("#button-critical").live("click",function(){a.incrementCount("starRating-critical")});e.$("#button-avp_only_reviews").live("click",function(){a.incrementCount("verified-purchases-click")});e.$("#button-media_reviews_only").live("click",function(){a.incrementCount("media-filter-click")})});"use strict";g.when("cr-A",
"cr-lighthut-terms-view","reviews-constants","cr-log-utils","cr-register-helper","ready").execute(function(e,f,a,d,g){g("cr-lighthut-terms-controller",function(){function c(a){a&&a.filterByKeyword!==n&&(f.setSelected(a.filterByKeyword),d.incrementCount("LighthutTermClicked"))}e.on(a.events.FILTER_APPLY_BEGIN,e.compositeEventWrapper(function(a){a&&a.data&&c(a.data)}));return{onFilterApplied:c}})});"use strict";g.when("A","cr-jQuery","cr-register-helper","ready").execute(function(e,f,a){a("cr-lighthut-terms-view",
function(){return{setSelected:function(a){a=a.replace(/ /g,"_");var d=(a=f("#cr-lighthouse-term-"+a))&&a.hasClass("cr-lighthut-term-selected");f(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||a.addClass("cr-lighthut-term-selected")}}})})});
/* ******** */
/*
 This software is used under the MIT license.

 URI.js - Mutating URLs

 Version: 1.14.1

 Author: Rodney Rehm
 Web: http://medialize.github.io/URI.js/

 Licensed under
   MIT License http://www.opensource.org/licenses/mit-license
   GPL v3 http://opensource.org/licenses/GPL-3.0

*/
P.register("3p-urijs",function(){(function(n,t){"object"===typeof exports?module.exports=t(require("./punycode"),require("./IPv6"),require("./SecondLevelDomains")):"function"===typeof define&&define.amd?define(["./punycode","./IPv6","./SecondLevelDomains"],t):n.URI=t(n.punycode,n.IPv6,n.SecondLevelDomains,n)})(this,function(n,t,r,k){function d(a,b){if(!(this instanceof d))return new d(a,b);void 0===a&&(a="undefined"!==typeof location?location.href+"":"");this.href(a);return void 0!==b?this.absoluteTo(b):
this}function q(a){return a.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function w(a){return void 0===a?"Undefined":String(Object.prototype.toString.call(a)).slice(8,-1)}function h(a){return"Array"===w(a)}function v(a,b){var c;if(h(b)){var d=0;for(c=b.length;d<c;d++)if(!v(a,b[d]))return!1;return!0}var f=w(b);d=0;for(c=a.length;d<c;d++)if("RegExp"===f){if("string"===typeof a[d]&&a[d].match(b))return!0}else if(a[d]===b)return!0;return!1}function z(a,b){if(!h(a)||!h(b)||a.length!==b.length)return!1;
a.sort();b.sort();for(var c=0,d=a.length;c<d;c++)if(a[c]!==b[c])return!1;return!0}function D(a){return escape(a)}function x(a){return encodeURIComponent(a).replace(/[!'()*]/g,D).replace(/\*/g,"%2A")}function u(a){return function(b,c){if(void 0===b)return this._parts[a]||"";this._parts[a]=b||null;this.build(!c);return this}}function A(a,b){return function(c,d){if(void 0===c)return this._parts[a]||"";null!==c&&(c+="",c.charAt(0)===b&&(c=c.substring(1)));this._parts[a]=c;this.build(!d);return this}}
var E=k&&k.URI;d.version="1.14.1";var e=d.prototype,p=Object.prototype.hasOwnProperty;d._parts=function(){return{protocol:null,username:null,password:null,hostname:null,urn:null,port:null,path:null,query:null,fragment:null,duplicateQueryParameters:d.duplicateQueryParameters,escapeQuerySpace:d.escapeQuerySpace}};d.duplicateQueryParameters=!1;d.escapeQuerySpace=!0;d.protocol_expression=/^[a-z][a-z0-9.+-]*$/i;d.idn_expression=/[^a-z0-9\.-]/i;d.punycode_expression=/(xn--)/i;d.ip4_expression=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;
d.ip6_expression=/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/;
d.find_uri_expression=/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))/ig;d.findUri={start:/\b(?:([a-z][a-z0-9.+-]*:\/\/)|www\.)/gi,end:/[\s\r\n]|$/,trim:/[`!()\[\]{};:'".,<>?«»“”„‘’]+$/};d.defaultPorts={http:"80",https:"443",ftp:"21",gopher:"70",ws:"80",wss:"443"};d.invalid_hostname_characters=/[^a-zA-Z0-9\.-]/;d.domAttributes={a:"href",blockquote:"cite",
link:"href",base:"href",script:"src",form:"action",img:"src",area:"href",iframe:"src",embed:"src",source:"src",track:"src",input:"src",audio:"src",video:"src"};d.getDomAttribute=function(a){if(a&&a.nodeName){var b=a.nodeName.toLowerCase();if("input"!==b||"image"===a.type)return d.domAttributes[b]}};d.encode=x;d.decode=decodeURIComponent;d.iso8859=function(){d.encode=escape;d.decode=unescape};d.unicode=function(){d.encode=x;d.decode=decodeURIComponent};d.characters={pathname:{encode:{expression:/%(24|26|2B|2C|3B|3D|3A|40)/ig,
map:{"%24":"$","%26":"\x26","%2B":"+","%2C":",","%3B":";","%3D":"\x3d","%3A":":","%40":"@"}},decode:{expression:/[\/\?#]/g,map:{"/":"%2F","?":"%3F","#":"%23"}}},reserved:{encode:{expression:/%(21|23|24|26|27|28|29|2A|2B|2C|2F|3A|3B|3D|3F|40|5B|5D)/ig,map:{"%3A":":","%2F":"/","%3F":"?","%23":"#","%5B":"[","%5D":"]","%40":"@","%21":"!","%24":"$","%26":"\x26","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",","%3B":";","%3D":"\x3d"}}}};d.encodeQuery=function(a,b){a=d.encode(a+"");void 0===b&&
(b=d.escapeQuerySpace);return b?a.replace(/%20/g,"+"):a};d.decodeQuery=function(a,b){a+="";void 0===b&&(b=d.escapeQuerySpace);try{return d.decode(b?a.replace(/\+/g,"%20"):a)}catch(c){return a}};d.recodePath=function(a){a=(a+"").split("/");for(var b=0,c=a.length;b<c;b++)a[b]=d.encodePathSegment(d.decode(a[b]));return a.join("/")};d.decodePath=function(a){a=(a+"").split("/");for(var b=0,c=a.length;b<c;b++)a[b]=d.decodePathSegment(a[b]);return a.join("/")};var B={encode:"encode",decode:"decode"},y,C=
function(a,b){return function(c){try{return d[b](c+"").replace(d.characters[a][b].expression,function(c){return d.characters[a][b].map[c]})}catch(g){return c}}};for(y in B)d[y+"PathSegment"]=C("pathname",B[y]);d.encodeReserved=C("reserved","encode");d.parse=function(a,b){b||(b={});var c=a.indexOf("#");-1<c&&(b.fragment=a.substring(c+1)||null,a=a.substring(0,c));c=a.indexOf("?");-1<c&&(b.query=a.substring(c+1)||null,a=a.substring(0,c));"//"===a.substring(0,2)?(b.protocol=null,a=a.substring(2),a=d.parseAuthority(a,
b)):(c=a.indexOf(":"),-1<c&&(b.protocol=a.substring(0,c)||null,b.protocol&&!b.protocol.match(d.protocol_expression)?b.protocol=void 0:"//"===a.substring(c+1,c+3)?(a=a.substring(c+3),a=d.parseAuthority(a,b)):(a=a.substring(c+1),b.urn=!0)));b.path=a;return b};d.parseHost=function(a,b){var c=a.indexOf("/");-1===c&&(c=a.length);if("["===a.charAt(0)){var d=a.indexOf("]");b.hostname=a.substring(1,d)||null;b.port=a.substring(d+2,c)||null;"/"===b.port&&(b.port=null)}else a.indexOf(":")!==a.lastIndexOf(":")?
(b.hostname=a.substring(0,c)||null,b.port=null):(d=a.substring(0,c).split(":"),b.hostname=d[0]||null,b.port=d[1]||null);b.hostname&&"/"!==a.substring(c).charAt(0)&&(c++,a="/"+a);return a.substring(c)||"/"};d.parseAuthority=function(a,b){a=d.parseUserinfo(a,b);return d.parseHost(a,b)};d.parseUserinfo=function(a,b){var c=a.indexOf("/"),g=a.lastIndexOf("@",-1<c?c:a.length-1);-1<g&&(-1===c||g<c)?(c=a.substring(0,g).split(":"),b.username=c[0]?d.decode(c[0]):null,c.shift(),b.password=c[0]?d.decode(c.join(":")):
null,a=a.substring(g+1)):(b.username=null,b.password=null);return a};d.parseQuery=function(a,b){if(!a)return{};a=a.replace(/&+/g,"\x26").replace(/^\?*&*|&+$/g,"");if(!a)return{};var c={};a=a.split("\x26");for(var g=a.length,f,e,l=0;l<g;l++)f=a[l].split("\x3d"),e=d.decodeQuery(f.shift(),b),f=f.length?d.decodeQuery(f.join("\x3d"),b):null,p.call(c,e)?("string"===typeof c[e]&&(c[e]=[c[e]]),c[e].push(f)):c[e]=f;return c};d.build=function(a){var b="";a.protocol&&(b+=a.protocol+":");a.urn||!b&&!a.hostname||
(b+="//");b+=d.buildAuthority(a)||"";"string"===typeof a.path&&("/"!==a.path.charAt(0)&&"string"===typeof a.hostname&&(b+="/"),b+=a.path);"string"===typeof a.query&&a.query&&(b+="?"+a.query);"string"===typeof a.fragment&&a.fragment&&(b+="#"+a.fragment);return b};d.buildHost=function(a){var b="";if(a.hostname)b=d.ip6_expression.test(a.hostname)?b+("["+a.hostname+"]"):b+a.hostname;else return"";a.port&&(b+=":"+a.port);return b};d.buildAuthority=function(a){return d.buildUserinfo(a)+d.buildHost(a)};
d.buildUserinfo=function(a){var b="";a.username&&(b+=d.encode(a.username),a.password&&(b+=":"+d.encode(a.password)),b+="@");return b};d.buildQuery=function(a,b,c){var g="",f,e;for(f in a)if(p.call(a,f)&&f)if(h(a[f])){var l={};var m=0;for(e=a[f].length;m<e;m++)void 0!==a[f][m]&&void 0===l[a[f][m]+""]&&(g+="\x26"+d.buildQueryParameter(f,a[f][m],c),!0!==b&&(l[a[f][m]+""]=!0))}else void 0!==a[f]&&(g+="\x26"+d.buildQueryParameter(f,a[f],c));return g.substring(1)};d.buildQueryParameter=function(a,b,c){return d.encodeQuery(a,
c)+(null!==b?"\x3d"+d.encodeQuery(b,c):"")};d.addQuery=function(a,b,c){if("object"===typeof b)for(var g in b)p.call(b,g)&&d.addQuery(a,g,b[g]);else if("string"===typeof b)void 0===a[b]?a[b]=c:("string"===typeof a[b]&&(a[b]=[a[b]]),h(c)||(c=[c]),a[b]=(a[b]||[]).concat(c));else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");};d.removeQuery=function(a,b,c){var g;if(h(b))for(c=0,g=b.length;c<g;c++)a[b[c]]=void 0;else if("object"===typeof b)for(g in b)p.call(b,g)&&
d.removeQuery(a,g,b[g]);else if("string"===typeof b)if(void 0!==c)if(a[b]===c)a[b]=void 0;else{if(h(a[b])){g=a[b];var f={},e;if(h(c)){var l=0;for(e=c.length;l<e;l++)f[c[l]]=!0}else f[c]=!0;l=0;for(e=g.length;l<e;l++)void 0!==f[g[l]]&&(g.splice(l,1),e--,l--);a[b]=g}}else a[b]=void 0;else throw new TypeError("URI.addQuery() accepts an object, string as the first parameter");};d.hasQuery=function(a,b,c,g){if("object"===typeof b){for(var f in b)if(p.call(b,f)&&!d.hasQuery(a,f,b[f]))return!1;return!0}if("string"!==
typeof b)throw new TypeError("URI.hasQuery() accepts an object, string as the name parameter");switch(w(c)){case "Undefined":return b in a;case "Boolean":return a=!(h(a[b])?!a[b].length:!a[b]),c===a;case "Function":return!!c(a[b],b,a);case "Array":return h(a[b])?(g?v:z)(a[b],c):!1;case "RegExp":return h(a[b])?g?v(a[b],c):!1:!(!a[b]||!a[b].match(c));case "Number":c=String(c);case "String":return h(a[b])?g?v(a[b],c):!1:a[b]===c;default:throw new TypeError("URI.hasQuery() accepts undefined, boolean, string, number, RegExp, Function as the value parameter");
}};d.commonPath=function(a,b){var c=Math.min(a.length,b.length),d;for(d=0;d<c;d++)if(a.charAt(d)!==b.charAt(d)){d--;break}if(1>d)return a.charAt(0)===b.charAt(0)&&"/"===a.charAt(0)?"/":"";if("/"!==a.charAt(d)||"/"!==b.charAt(d))d=a.substring(0,d).lastIndexOf("/");return a.substring(0,d+1)};d.withinString=function(a,b,c){c||(c={});var g=c.start||d.findUri.start,f=c.end||d.findUri.end,e=c.trim||d.findUri.trim,l=/[a-z0-9-]=["']?$/i;for(g.lastIndex=0;;){var m=g.exec(a);if(!m)break;m=m.index;if(c.ignoreHtml){var h=
a.slice(Math.max(m-3,0),m);if(h&&l.test(h))continue}h=m+a.slice(m).search(f);var k=a.slice(m,h).replace(e,"");c.ignore&&c.ignore.test(k)||(h=m+k.length,k=b(k,m,h,a),a=a.slice(0,m)+k+a.slice(h),g.lastIndex=m+k.length)}g.lastIndex=0;return a};d.ensureValidHostname=function(a){if(a.match(d.invalid_hostname_characters)){if(!n)throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-] and Punycode.js is not available');if(n.toASCII(a).match(d.invalid_hostname_characters))throw new TypeError('Hostname "'+
a+'" contains characters other than [A-Z0-9.-]');}};d.noConflict=function(a){if(a)return a={URI:this.noConflict()},k.URITemplate&&"function"===typeof k.URITemplate.noConflict&&(a.URITemplate=k.URITemplate.noConflict()),k.IPv6&&"function"===typeof k.IPv6.noConflict&&(a.IPv6=k.IPv6.noConflict()),k.SecondLevelDomains&&"function"===typeof k.SecondLevelDomains.noConflict&&(a.SecondLevelDomains=k.SecondLevelDomains.noConflict()),a;k.URI===this&&(k.URI=E);return this};e.build=function(a){if(!0===a)this._deferred_build=
!0;else if(void 0===a||this._deferred_build)this._string=d.build(this._parts),this._deferred_build=!1;return this};e.clone=function(){return new d(this)};e.valueOf=e.toString=function(){return this.build(!1)._string};e.protocol=u("protocol");e.username=u("username");e.password=u("password");e.hostname=u("hostname");e.port=u("port");e.query=A("query","?");e.fragment=A("fragment","#");e.search=function(a,b){a=this.query(a,b);return"string"===typeof a&&a.length?"?"+a:a};e.hash=function(a,b){a=this.fragment(a,
b);return"string"===typeof a&&a.length?"#"+a:a};e.pathname=function(a,b){if(void 0===a||!0===a)return b=this._parts.path||(this._parts.hostname?"/":""),a?d.decodePath(b):b;this._parts.path=a?d.recodePath(a):"/";this.build(!b);return this};e.path=e.pathname;e.href=function(a,b){var c;if(void 0===a)return this.toString();this._string="";this._parts=d._parts();var g=a instanceof d,f="object"===typeof a&&(a.hostname||a.path||a.pathname);a.nodeName&&(f=d.getDomAttribute(a),a=a[f]||"",f=!1);!g&&f&&void 0!==
a.pathname&&(a=a.toString());if("string"===typeof a||a instanceof String)this._parts=d.parse(String(a),this._parts);else if(g||f)for(c in a=g?a._parts:a,a)p.call(this._parts,c)&&(this._parts[c]=a[c]);else throw new TypeError("invalid input");this.build(!b);return this};e.is=function(a){var b=!1,c=!1,g=!1,f=!1,e=!1,l=!1,h=!1,k=!this._parts.urn;this._parts.hostname&&(k=!1,c=d.ip4_expression.test(this._parts.hostname),g=d.ip6_expression.test(this._parts.hostname),b=c||g,e=(f=!b)&&r&&r.has(this._parts.hostname),
l=f&&d.idn_expression.test(this._parts.hostname),h=f&&d.punycode_expression.test(this._parts.hostname));switch(a.toLowerCase()){case "relative":return k;case "absolute":return!k;case "domain":case "name":return f;case "sld":return e;case "ip":return b;case "ip4":case "ipv4":case "inet4":return c;case "ip6":case "ipv6":case "inet6":return g;case "idn":return l;case "url":return!this._parts.urn;case "urn":return!!this._parts.urn;case "punycode":return h}return null};var F=e.protocol,G=e.port,H=e.hostname;
e.protocol=function(a,b){if(void 0!==a&&a&&(a=a.replace(/:(\/\/)?$/,""),!a.match(d.protocol_expression)))throw new TypeError('Protocol "'+a+"\" contains characters other than [A-Z0-9.+-] or doesn't start with [A-Z]");return F.call(this,a,b)};e.scheme=e.protocol;e.port=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a&&(0===a&&(a=null),a&&(a+="",":"===a.charAt(0)&&(a=a.substring(1)),a.match(/[^0-9]/))))throw new TypeError('Port "'+a+'" contains characters other than [0-9]');
return G.call(this,a,b)};e.hostname=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a){var c={};d.parseHost(a,c);a=c.hostname}return H.call(this,a,b)};e.host=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?d.buildHost(this._parts):"";d.parseHost(a,this._parts);this.build(!b);return this};e.authority=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?d.buildAuthority(this._parts):
"";d.parseAuthority(a,this._parts);this.build(!b);return this};e.userinfo=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.username)return"";a=d.buildUserinfo(this._parts);return a.substring(0,a.length-1)}"@"!==a[a.length-1]&&(a+="@");d.parseUserinfo(a,this._parts);this.build(!b);return this};e.resource=function(a,b){if(void 0===a)return this.path()+this.search()+this.hash();a=d.parse(a);this._parts.path=a.path;this._parts.query=a.query;this._parts.fragment=
a.fragment;this.build(!b);return this};e.subdomain=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";a=this._parts.hostname.length-this.domain().length-1;return this._parts.hostname.substring(0,a)||""}var c=this._parts.hostname.length-this.domain().length;c=this._parts.hostname.substring(0,c);c=new RegExp("^"+q(c));a&&"."!==a.charAt(a.length-1)&&(a+=".");a&&d.ensureValidHostname(a);this._parts.hostname=this._parts.hostname.replace(c,
a);this.build(!b);return this};e.domain=function(a,b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";if((a=this._parts.hostname.match(/\./g))&&2>a.length)return this._parts.hostname;b=this._parts.hostname.length-this.tld(b).length-1;b=this._parts.hostname.lastIndexOf(".",b-1)+1;return this._parts.hostname.substring(b)||""}if(!a)throw new TypeError("cannot set domain empty");d.ensureValidHostname(a);
if(!this._parts.hostname||this.is("IP"))this._parts.hostname=a;else{var c=new RegExp(q(this.domain())+"$");this._parts.hostname=this._parts.hostname.replace(c,a)}this.build(!b);return this};e.tld=function(a,b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";a=this._parts.hostname.lastIndexOf(".");a=this._parts.hostname.substring(a+1);return!0!==b&&r&&r.list[a.toLowerCase()]?r.get(this._parts.hostname)||
a:a}if(a)if(a.match(/[^a-zA-Z0-9-]/))if(r&&r.is(a)){var c=new RegExp(q(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(c,a)}else throw new TypeError('TLD "'+a+'" contains characters other than [A-Z0-9]');else{if(!this._parts.hostname||this.is("IP"))throw new ReferenceError("cannot set TLD on non-domain host");c=new RegExp(q(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(c,a)}else throw new TypeError("cannot set TLD empty");this.build(!b);return this};e.directory=
function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path&&!this._parts.hostname)return"";if("/"===this._parts.path)return"/";b=this._parts.path.length-this.filename().length-1;b=this._parts.path.substring(0,b)||(this._parts.hostname?"/":"");return a?d.decodePath(b):b}var c=this._parts.path.length-this.filename().length;c=this._parts.path.substring(0,c);c=new RegExp("^"+q(c));this.is("relative")||(a||(a="/"),"/"!==a.charAt(0)&&(a="/"+a));a&&"/"!==a.charAt(a.length-
1)&&(a+="/");a=d.recodePath(a);this._parts.path=this._parts.path.replace(c,a);this.build(!b);return this};e.filename=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";b=this._parts.path.lastIndexOf("/");b=this._parts.path.substring(b+1);return a?d.decodePathSegment(b):b}var c=!1;"/"===a.charAt(0)&&(a=a.substring(1));a.match(/\.?\//)&&(c=!0);var g=new RegExp(q(this.filename())+"$");a=d.recodePath(a);this._parts.path=
this._parts.path.replace(g,a);c?this.normalizePath(b):this.build(!b);return this};e.suffix=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";b=this.filename();var c=b.lastIndexOf(".");if(-1===c)return"";b=b.substring(c+1);b=/^[a-z0-9%]+$/i.test(b)?b:"";return a?d.decodePathSegment(b):b}"."===a.charAt(0)&&(a=a.substring(1));c=this.suffix();if(c)var g=a?new RegExp(q(c)+"$"):new RegExp(q("."+c)+"$");else{if(!a)return this;
this._parts.path+="."+d.recodePath(a)}g&&(a=d.recodePath(a),this._parts.path=this._parts.path.replace(g,a));this.build(!b);return this};e.segment=function(a,b,c){var d=this._parts.urn?":":"/",f=this.path(),e="/"===f.substring(0,1);f=f.split(d);void 0!==a&&"number"!==typeof a&&(c=b,b=a,a=void 0);if(void 0!==a&&"number"!==typeof a)throw Error('Bad segment "'+a+'", must be 0-based integer');e&&f.shift();0>a&&(a=Math.max(f.length+a,0));if(void 0===b)return void 0===a?f:f[a];if(null===a||void 0===f[a])if(h(b)){f=
[];a=0;for(var l=b.length;a<l;a++)if(b[a].length||f.length&&f[f.length-1].length)f.length&&!f[f.length-1].length&&f.pop(),f.push(b[a])}else{if(b||"string"===typeof b)""===f[f.length-1]?f[f.length-1]=b:f.push(b)}else b?f[a]=b:f.splice(a,1);e&&f.unshift("");return this.path(f.join(d),c)};e.segmentCoded=function(a,b,c){var e;"number"!==typeof a&&(c=b,b=a,a=void 0);if(void 0===b){a=this.segment(a,b,c);if(h(a)){var f=0;for(e=a.length;f<e;f++)a[f]=d.decode(a[f])}else a=void 0!==a?d.decode(a):void 0;return a}if(h(b))for(f=
0,e=b.length;f<e;f++)b[f]=d.decode(b[f]);else b="string"===typeof b||b instanceof String?d.encode(b):b;return this.segment(a,b,c)};var I=e.query;e.query=function(a,b){if(!0===a)return d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);if("function"===typeof a){var c=d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);a=a.call(this,c);this._parts.query=d.buildQuery(a||c,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);this.build(!b);return this}return void 0!==
a&&"string"!==typeof a?(this._parts.query=d.buildQuery(a,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace),this.build(!b),this):I.call(this,a,b)};e.setQuery=function(a,b,c){var e=d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);if("string"===typeof a||a instanceof String)e[a]=void 0!==b?b:null;else if("object"===typeof a)for(var f in a)p.call(a,f)&&(e[f]=a[f]);else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");this._parts.query=
d.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(c=b);this.build(!c);return this};e.addQuery=function(a,b,c){var e=d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);d.addQuery(e,a,void 0===b?null:b);this._parts.query=d.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(c=b);this.build(!c);return this};e.removeQuery=function(a,b,c){var e=d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);
d.removeQuery(e,a,b);this._parts.query=d.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(c=b);this.build(!c);return this};e.hasQuery=function(a,b,c){var e=d.parseQuery(this._parts.query,this._parts.escapeQuerySpace);return d.hasQuery(e,a,b,c)};e.setSearch=e.setQuery;e.addSearch=e.addQuery;e.removeSearch=e.removeQuery;e.hasSearch=e.hasQuery;e.normalize=function(){return this._parts.urn?this.normalizeProtocol(!1).normalizeQuery(!1).normalizeFragment(!1).build():
this.normalizeProtocol(!1).normalizeHostname(!1).normalizePort(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build()};e.normalizeProtocol=function(a){"string"===typeof this._parts.protocol&&(this._parts.protocol=this._parts.protocol.toLowerCase(),this.build(!a));return this};e.normalizeHostname=function(a){this._parts.hostname&&(this.is("IDN")&&n?this._parts.hostname=n.toASCII(this._parts.hostname):this.is("IPv6")&&t&&(this._parts.hostname=t.best(this._parts.hostname)),this._parts.hostname=
this._parts.hostname.toLowerCase(),this.build(!a));return this};e.normalizePort=function(a){"string"===typeof this._parts.protocol&&this._parts.port===d.defaultPorts[this._parts.protocol]&&(this._parts.port=null,this.build(!a));return this};e.normalizePath=function(a){if(this._parts.urn||!this._parts.path||"/"===this._parts.path)return this;var b=this._parts.path,c="";if("/"!==b.charAt(0)){var e=!0;b="/"+b}b=b.replace(/(\/(\.\/)+)|(\/\.$)/g,"/").replace(/\/{2,}/g,"/");e&&(c=b.substring(1).match(/^(\.\.\/)+/)||
"")&&(c=c[0]);for(;;){var f=b.indexOf("/..");if(-1===f)break;else if(0===f){b=b.substring(3);continue}var h=b.substring(0,f).lastIndexOf("/");-1===h&&(h=f);b=b.substring(0,h)+b.substring(f+3)}e&&this.is("relative")&&(b=c+b.substring(1));b=d.recodePath(b);this._parts.path=b;this.build(!a);return this};e.normalizePathname=e.normalizePath;e.normalizeQuery=function(a){"string"===typeof this._parts.query&&(this._parts.query.length?this.query(d.parseQuery(this._parts.query,this._parts.escapeQuerySpace)):
this._parts.query=null,this.build(!a));return this};e.normalizeFragment=function(a){this._parts.fragment||(this._parts.fragment=null,this.build(!a));return this};e.normalizeSearch=e.normalizeQuery;e.normalizeHash=e.normalizeFragment;e.iso8859=function(){var a=d.encode,b=d.decode;d.encode=escape;d.decode=decodeURIComponent;this.normalize();d.encode=a;d.decode=b;return this};e.unicode=function(){var a=d.encode,b=d.decode;d.encode=x;d.decode=unescape;this.normalize();d.encode=a;d.decode=b;return this};
e.readable=function(){var a=this.clone();a.username("").password("").normalize();var b="";a._parts.protocol&&(b+=a._parts.protocol+"://");a._parts.hostname&&(a.is("punycode")&&n?(b+=n.toUnicode(a._parts.hostname),a._parts.port&&(b+=":"+a._parts.port)):b+=a.host());a._parts.hostname&&a._parts.path&&"/"!==a._parts.path.charAt(0)&&(b+="/");b+=a.path(!0);if(a._parts.query){for(var c="",e=0,f=a._parts.query.split("\x26"),h=f.length;e<h;e++){var l=(f[e]||"").split("\x3d");c+="\x26"+d.decodeQuery(l[0],this._parts.escapeQuerySpace).replace(/&/g,
"%26");void 0!==l[1]&&(c+="\x3d"+d.decodeQuery(l[1],this._parts.escapeQuerySpace).replace(/&/g,"%26"))}b+="?"+c.substring(1)}return b+=d.decodeQuery(a.hash(),!0)};e.absoluteTo=function(a){var b=this.clone(),c=["protocol","username","password","hostname","port"],e,f;if(this._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a instanceof d||(a=new d(a));b._parts.protocol||(b._parts.protocol=a._parts.protocol);if(this._parts.hostname)return b;for(e=0;f=c[e];e++)b._parts[f]=
a._parts[f];b._parts.path?".."===b._parts.path.substring(-2)&&(b._parts.path+="/"):(b._parts.path=a._parts.path,b._parts.query||(b._parts.query=a._parts.query));"/"!==b.path().charAt(0)&&(a=a.directory(),b._parts.path=(a?a+"/":"")+b._parts.path,b.normalizePath());b.build();return b};e.relativeTo=function(a){var b=this.clone().normalize();if(b._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a=(new d(a)).normalize();var c=b._parts;var e=a._parts;var f=b.path();
var h=a.path();if("/"!==f.charAt(0))throw Error("URI is already relative");if("/"!==h.charAt(0))throw Error("Cannot calculate a URI relative to another relative URI");c.protocol===e.protocol&&(c.protocol=null);if(c.username===e.username&&c.password===e.password&&null===c.protocol&&null===c.username&&null===c.password&&c.hostname===e.hostname&&c.port===e.port)c.hostname=null,c.port=null;else return b.build();if(f===h)return c.path="",b.build();a=d.commonPath(b.path(),a.path());if(!a)return b.build();
e=e.path.substring(a.length).replace(/[^\/]*$/,"").replace(/.*?\//g,"../");c.path=e+c.path.substring(a.length);return b.build()};e.equals=function(a){var b=this.clone(),c=new d(a);a={};var e;b.normalize();c.normalize();if(b.toString()===c.toString())return!0;var f=b.query();var k=c.query();b.query("");c.query("");if(b.toString()!==c.toString()||f.length!==k.length)return!1;b=d.parseQuery(f,this._parts.escapeQuerySpace);k=d.parseQuery(k,this._parts.escapeQuerySpace);for(e in b)if(p.call(b,e)){if(!h(b[e])){if(b[e]!==
k[e])return!1}else if(!z(b[e],k[e]))return!1;a[e]=!0}for(e in k)if(p.call(k,e)&&!a[e])return!1;return!0};e.duplicateQueryParameters=function(a){this._parts.duplicateQueryParameters=!!a;return this};e.escapeQuerySpace=function(a){this._parts.escapeQuerySpace=!!a;return this};return d});return URI});
/* ******** */
