window.aui.amd_define("@amzn/kata-web-framework-logger",["exports"],function(r){"use strict";const a=()=>{var n;return(n=!1)!==null&&n!==void 0?n:!1},f=()=>!0,m=()=>!1,E=()=>window.ueLogError,b=n=>console[n];function t({code:n,e,context:o,level:d="ERROR"}){const l=E(),u=b(I[d]),g=o==null?void 0:o.templateUuid;if(l&&f()){const c={logLevel:d,attribution:"HtmlKataWebFrameworkJs",message:g?`${n}:${g}`:n};e instanceof Error?l(e,c):l(c),a()&&u(n,e,{...c,...o})}else a()?u(n,e,o):u(n,e)}const I={FATAL:"error",ERROR:"error",WARN:"warn"},L=(n,e,o)=>{t({code:n,e,context:o,level:"ERROR"})},i=(n,e,o)=>{t({code:n,e,context:o,level:"WARN"})},R=(n,e,o)=>{t({code:n,e,context:o,level:"FATAL"})},v=()=>{},A=(n,e,o)=>{e.has(n)?i(o):e.add(n)};let s=!1;const w=()=>window.fm?window.fm:(s||(i("K067"),s=!0),{recordInstrumentationEvent:()=>{},now:()=>0});function K(n,e){const o=w();o.recordInstrumentationEvent(n,e!=null?e:o.now())}const T=()=>typeof window.uex!="function"?()=>{}:window.uex,k=()=>!window.ue||typeof window.ue.count!="function"?()=>{}:window.ue.count;function C(){T()("ld","kwf",{wb:1})}function y(){k()("kwf.enabled",1)}r.countKwfEnabled=y,r.enableErrorContext=a,r.enableJsErrors=f,r.enableTiming=m,r.error=L,r.fatal=R,r.fmInstance=w,r.log=t,r.recordMetric=K,r.reportKwfLoaded=C,r.timing=v,r.warn=i,r.warnIfDuplicate=A,Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-register",["exports","@amzn/kata-web-framework-logger"],function(o,u){"use strict";const s=Object.create(null),w=new Set,K=e=>{const r=e.split(":")[1];return(r==null?void 0:r.split(",")[0])||""},k=(e,r)=>{var t;return s[e]=(t=s[e])!==null&&t!==void 0?t:C(r,e),s[e].config!==r&&u.log({code:"K031",context:{uuid:e,config:r}}),s[e]},m=(e,...r)=>k(P(e,...r),e),C=(e,r)=>{let t,i,l=!1;const a=Object.create(null);let R=!1,c;const U=()=>{const n=K(r);return w.has(n)?(w.delete(n),u.warn("K079",null,{uuid:r}),!0):!1},_=n=>{var d,p,f;if(t){if(U())return;u.warn((d=e.diagnostics.alreadyProvidedWarn)!==null&&d!==void 0?d:"K005",null,{uuid:r,...a});return}if(i){if(U())return;u.warn((p=e.diagnostics.alreadyFailedWarn)!==null&&p!==void 0?p:"K006",null,{uuid:r,...a});return}if(l){u.error((f=e.diagnostics.alreadyReleasedWarn)!==null&&f!==void 0?f:"K009",null,{uuid:r,...a});return}n()},g=n=>{_(()=>{t=n,R=!0})},j=n=>{_(()=>{i=n})},y=()=>{if(l)return;c=void 0,t=void 0,i=void 0,l=!0,R=!1;for(const d of Object.keys(a))delete a[d];const n=K(r);n&&w.add(n),delete s[r]},T={uuid:r,provide:g,fail:j,release:y,isProvided:()=>R,assertReleased:()=>{if(!l&&!e.willNotBeReleased)throw new Error("K057")},promise:()=>(c||(i?c=Promise.reject(i):t?c=Promise.resolve(t):l?c=Promise.reject(new Error("K058")):c=new Promise((n,d)=>{const p=S(e,r,a),f=()=>{p.forEach(v=>clearTimeout(v))};T.provide=v=>{g(v),n(v),f()},T.fail=v=>{j(v),d(v),f()},T.release=()=>{y(),d(new Error("K058")),f()}})),e.singleConsumer&&(c=c.finally(y)),c),config:e,diagnosticContext:a,setDiagnosticContext:(n,d)=>{a[n]=d}};return T},P=(e,...r)=>`${e.namespace}:${r.join(",")}`,N=(e,r)=>{const t=`${e}:`,i=[];for(const l in s)if(l.startsWith(t)){if(r!=null&&r.unprovided&&s[l].isProvided())continue;i.push(l)}return i},E=e=>{for(const r of e)s[r]&&s[r].release()},O=e=>{for(const r in s){const t=r;e&&s[t].assertReleased(),s[t].release(),delete s[t]}},b=()=>{w.clear()},I=3e3,M=3e4,S=({timeouts:e,diagnostics:r},t,i)=>{var l,a;const R=setTimeout(()=>{u.warn(r.timeout,null,{uuid:t,...i})},(l=e==null?void 0:e.warn)!==null&&l!==void 0?l:I),c=setTimeout(()=>{u.error(r.timeout,null,{uuid:t,...i})},(a=e==null?void 0:e.error)!==null&&a!==void 0?a:M);return[R,c]},h={namespace:"ext",diagnostics:{timeout:"K059"},willNotBeReleased:!0},B={namespace:"template",diagnostics:{timeout:"K001"},willNotBeReleased:!0},$=(e,r)=>m(B,e).provide(r),z=e=>m(B,e).promise(),A=(e,r)=>m(h,e).provide(r),D=e=>m(h,e).promise();o.createUuid=P,o.externalLookup=D,o.externalRegister=A,o.getTrackedByNamespace=N,o.lookup=z,o.register=$,o.release=E,o.track=k,o.trackByIds=m,o.unsafeClearReleasedRenderUuids=b,o.unsafeReleaseAll=O,Object.defineProperty(o,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-functions",["@amzn/kata-web-framework-runtime-utils"],function(n){"use strict";const t=()=>{},e=i=>i;return()=>({unsupportedFn:n.unsupportedFn,voidFn:t,identityFn:e})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-utils",["exports","@amzn/kata-web-framework-logger"],function(n,t){"use strict";const c=(...r)=>r.flat(1/0).join(""),s=(...r)=>r.join(" ").trim().replace(/\s+/g," "),u=(r,e)=>(r%e+e)%e,l=(r,e)=>({get:()=>r.read(e),set:i=>{r.defer(()=>{try{r.write(e,i)}catch(g){t.error("K063",g,{value:e,newValue:i})}})}}),f=(r,e)=>({get:()=>r,set:e}),m=r=>({discriminator:o(r),value:r,reflection:typeof r}),o=r=>{var e;return(e=r==null?void 0:r.__type)!==null&&e!==void 0?e:r==null?void 0:r.runtimeDataType},y=(r,e)=>e.map(i=>`${i}=${a(r,i)}`).join("&"),a=(r,e)=>{switch(e){case"discriminator":return o(r);case"value":return r;case"reflection":return typeof r;case"length":return Array.isArray(r)?r.length:null}},d=()=>{t.error("K041")};n.box=l,n.classes=s,n.describeExpr=y,n.discriminators=m,n.flattenToString=c,n.mod=u,n.reBox=f,n.unsupportedFn=d,Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
